/** Lessons: what goes on the boards, which pictures and videos the projector shows, which interactive 3D lab to try, and the answers to student questions. */
import type { Subject } from "../game/types";
export interface LabRef { id: string; cfg?: string; title: string; intro: string }
export interface LessonDef {
  id: string; subject: Subject; title: string; blurb: string; points: string[]; examples: string[]; pics: string[]; videos: string[]; lab: LabRef;
  intro: string; wrap: string; homework: string; glossary: Record<string, string>; whys: string[];
  /** extra (catch-up) lessons only: 0 = K-2, 1 = grades 3-5, 2 = grades 6-8 */ band?: number; extra?: boolean;
  /** curriculum packs: the teacher's script, the textbook section this lesson links to, an elective course name, grade range and the pack it came from */
  script?: import("./packs").ScriptStep[]; bookRef?: string; elective?: string; grades?: string; pack?: string;
}
const L = (l: LessonDef) => l;
export const CURRICULUM: Record<Subject, LessonDef[]> = {
  math: [
    L({ id: "parabola", subject: "math", title: "Graphing a parabola", blurb: "Vertex, axis of symmetry and plotting.", pics: ["parabola", "orbit"], videos: ["parabola"],
      points: ["Parabola: the U-shaped curve of y = x²", "Vertex: the turning point (lowest or highest)", "Axis of symmetry: the line that splits the curve in two matching halves", "To graph: plot the vertex, find points, mirror them"],
      examples: ["y = x²: vertex (0, 0). x = 2 gives y = 4, and x = -2 gives y = 4 too.", "y = (x - 3)²: the curve slides 3 right, so the vertex is (3, 0).", "A tossed ball follows a parabola. The top of its flight is the vertex."],
      lab: { id: "parabola", title: "Parabola Launcher", intro: "Shape the curve with the sliders so the ball lands on the targets. Watch the vertex and the axis of symmetry move." },
      intro: "Today we're graphing parabolas, the curve you see whenever something is thrown.", wrap: "Great work. Remember: find the vertex, use the axis of symmetry, then mirror your points.", homework: "Graph y = x² + 2 and label the vertex and axis of symmetry.",
      glossary: { vertex: "The vertex is the turning point of the parabola, its highest or lowest point.", parabola: "A parabola is the U-shaped curve you get from a squared term, like y = x squared.", axis: "The axis of symmetry is the vertical line through the vertex that splits the graph into matching halves.", symmetry: "Symmetry means one side is a mirror image of the other.", intercept: "An intercept is where the graph crosses an axis.", coordinate: "A coordinate is a pair like (3, 4): across, then up.", root: "A root, or zero, is an x value where the graph touches the x-axis." },
      whys: ["It's symmetric because squaring makes a positive number and its negative give the same answer.", "The vertex is the turning point because that's where the curve stops going down and starts going up.", "Mirroring saves work: once you know one side, the other side is free."] }),
    L({ id: "fractions", subject: "math", title: "Fractions", blurb: "Equal parts of a whole.", pics: ["fractions", "pizza-fraction"], videos: ["fractions"],
      points: ["A fraction names equal parts of a whole", "Numerator: how many parts we have", "Denominator: how many equal parts in all", "Equivalent fractions name the same amount: 4/8 = 1/2"],
      examples: ["A pizza cut in 8: 3 slices is 3/8.", "2/4 and 1/2 are equivalent: half the circle either way.", "1/3 is bigger than 1/4: fewer cuts means bigger pieces."],
      lab: { id: "pizza", title: "Pizza Party", intro: "Serve each classmate exactly the fraction they ask for. Click the slices to hand them out." },
      intro: "Today: fractions. Parts of a whole, shared fairly.", wrap: "Nice sharing. Equal parts are what make fractions work.", homework: "Draw 3 shapes and shade 1/2, 1/4 and 3/4 of each.",
      glossary: { numerator: "The numerator is the top number: how many parts you have.", denominator: "The denominator is the bottom number: how many equal parts make the whole.", equivalent: "Equivalent fractions look different but are the same amount, like 2/4 and 1/2.", fraction: "A fraction is a number that names part of a whole.", whole: "The whole is the entire thing before it is divided." },
      whys: ["The parts must be equal, otherwise 1/4 wouldn't always mean the same amount.", "More pieces means smaller pieces, which is why 1/8 is smaller than 1/4.", "Equivalent fractions work because cutting each piece in half doubles both numbers."] }),
  ],
  ela: [
    L({ id: "theme", subject: "ela", title: "Finding the theme", blurb: "Plot, change and evidence.", pics: ["organizer"], videos: ["theme"],
      points: ["Ask: what happens? (the plot)", "Ask: what changes? (the character or situation)", "Back it up with evidence from the text", "A theme is a message, written as a full sentence"],
      examples: ["Theme: 'Slow and steady wins the race.'", "Evidence: the hare quit trying, the tortoise never stopped.", "Not a theme: 'friendship' (one word). A theme says something about it."],
      lab: { id: "cardsort", cfg: "tortoise", title: "Story Builder", intro: "Put the events of the story in order, then pick the theme the events prove." },
      intro: "Today we're finding themes: the big message hiding inside a story.", wrap: "Remember: plot, change, evidence, then state the theme in a sentence.", homework: "Write the theme of your favorite story in one sentence and add one piece of evidence.",
      glossary: { theme: "The theme is the big message or lesson of a story, written as a full sentence.", evidence: "Evidence is a detail or quote from the text that supports your idea.", plot: "The plot is the series of events in a story.", character: "A character is a person or creature in a story.", conflict: "Conflict is the problem or struggle that drives the story.", inference: "An inference is an idea you figure out from clues in the text." },
      whys: ["We use evidence so the theme is something we can show, not just a guess.", "Looking at what changes works because stories are about change, and the change points to the lesson.", "A theme is a message the author wants us to take away."] }),
    L({ id: "figurative", subject: "ela", title: "Simile and metaphor", blurb: "Creative comparisons.", pics: ["simile"], videos: ["figurative"],
      points: ["Figurative language paints pictures with words", "Simile: compares using LIKE or AS", "Metaphor: says one thing IS another", "Use them to make writing vivid"],
      examples: ["Simile: 'as busy as a bee.'", "Metaphor: 'time is a thief.'", "Simile: 'She runs like the wind.'"],
      lab: { id: "cardsort", cfg: "figurative", title: "Sort the Sayings", intro: "Drag each saying under Simile or Metaphor." },
      intro: "Today: figurative language, words that paint pictures.", wrap: "Like or as means simile. Is or are means metaphor.", homework: "Write two similes and two metaphors about your morning.",
      glossary: { simile: "A simile compares two things using 'like' or 'as.'", metaphor: "A metaphor says one thing is another to show a feeling, like 'Time is a thief.'", figurative: "Figurative language uses comparisons and imagery instead of literal meaning.", literal: "Literal means exactly what the words say.", imagery: "Imagery is language that appeals to the senses." },
      whys: ["Comparisons help readers picture and feel something new.", "Similes use like or as, so the comparison is easy to spot.", "Metaphors feel stronger because they say one thing actually is the other."] }),
    L({ id: "orchestra", subject: "ela", title: "Music: the orchestra", blurb: "Instrument families.", pics: ["staff"], videos: ["orchestra"],
      points: ["An orchestra has four instrument families", "Strings: violin, cello (sound from a bow or plucking)", "Woodwinds and brass: sound from blowing air", "Percussion: struck or shaken. The conductor keeps everyone together"],
      examples: ["Violin: strings. Flute: woodwind.", "Trumpet: brass. Drum: percussion.", "The conductor uses a baton to show the beat."],
      lab: { id: "cardsort", cfg: "orchestra", title: "Seat the Orchestra", intro: "Place each instrument in its family." },
      intro: "Welcome to music. Today we meet the orchestra.", wrap: "Four families, one conductor, one big sound.", homework: "Name two instruments from each family.",
      glossary: { conductor: "The conductor leads the orchestra and shows the tempo with a baton.", strings: "String instruments make sound from vibrating strings, like the violin.", woodwind: "Woodwinds make sound when air is blown across or through them, like the flute.", brass: "Brass instruments are blown through metal tubes, like the trumpet.", percussion: "Percussion instruments are struck or shaken, like drums.", orchestra: "An orchestra is a large group of musicians playing together." },
      whys: ["Families group instruments by how they make sound.", "A conductor keeps every player on the same beat.", "Different sounds blend to make a fuller sound."] }),
    L({ id: "rhythm", subject: "ela", title: "Music: beat and rhythm", blurb: "Counting in four.", pics: ["staff"], videos: ["rhythm"],
      points: ["Beat: the steady pulse of the music", "Rhythm: the pattern of long and short sounds", "Count 1-2-3-4 and clap on each beat", "A quarter note gets one beat"],
      examples: ["Clap on every beat: 1, 2, 3, 4.", "Two eighth notes fit in one beat.", "A metronome ticks the beat."],
      lab: { id: "beats", title: "Beat Pads", intro: "Hit the pads when the notes reach the line. Your classmate keeps the drum beat." },
      intro: "Today in music: feel the beat.", wrap: "Keep the steady beat and the rhythm will follow.", homework: "Clap the rhythm of your name.",
      glossary: { beat: "The beat is the steady pulse you can tap your foot to.", rhythm: "Rhythm is the pattern of long and short sounds.", tempo: "Tempo is how fast or slow the music goes.", note: "A note shows a sound and how long it lasts.", metronome: "A metronome ticks a steady beat." },
      whys: ["A steady beat lets everyone play together.", "Different note lengths make the rhythm interesting.", "Tempo changes the mood: fast feels excited, slow feels calm."] }),
    L({ id: "colormix", subject: "ela", title: "Art: mixing colors", blurb: "Primary and secondary colors.", pics: ["color-wheel"], videos: ["colormix"],
      points: ["Primary colors: red, yellow, blue", "Mix two primaries for a secondary color", "Red + yellow = orange. Yellow + blue = green. Blue + red = purple", "Warm colors feel cozy, cool colors feel calm"],
      examples: ["A sunset uses warm colors: red, orange, yellow.", "The ocean uses cool colors: blue and green.", "Adding white makes a color lighter."],
      lab: { id: "colormix", title: "Paint Mixer", intro: "Mix the paint to match each color swatch, then paint the cube." },
      intro: "Welcome to art. Today we mix colors.", wrap: "Three primaries can make a whole rainbow.", homework: "Paint a color wheel using only red, yellow and blue.",
      glossary: { primary: "Primary colors are red, yellow and blue. You cannot make them by mixing.", secondary: "Secondary colors are made by mixing two primaries: orange, green, purple.", warm: "Warm colors, like red and orange, feel cozy or energetic.", cool: "Cool colors, like blue and green, feel calm.", palette: "A palette is a board for mixing paint.", hue: "Hue is another word for color." },
      whys: ["Primaries can't be made from other colors, so they're the starting point.", "Mixing two primaries gives a secondary color halfway between them.", "Artists use warm and cool colors to set the mood."] }),
    L({ id: "perspective", subject: "ela", title: "Art: perspective", blurb: "Making flat drawings look deep.", pics: ["color-wheel"], videos: ["perspective"],
      points: ["Perspective makes a flat drawing look 3D", "Lines going away meet at the vanishing point", "Far things look smaller, near things look bigger", "Overlap shows what is in front"],
      examples: ["Railroad tracks meet at the horizon.", "Trees in the distance look tiny.", "A hand drawn over a face is closer than the face."],
      lab: { id: "cardsort", cfg: "perspective", title: "Near and Far", intro: "Sort the objects into foreground, middle and background." },
      intro: "In art today: perspective, the trick that makes a page look deep.", wrap: "Vanishing point, size change, overlap. Three tools for depth.", homework: "Draw a road that disappears into the distance.",
      glossary: { perspective: "Perspective is a way to show depth on a flat surface.", horizon: "The horizon is the line where the ground meets the sky.", vanishing: "The vanishing point is where lines going away from you appear to meet.", foreground: "The foreground is the part of a picture closest to you.", background: "The background is the part farthest away." },
      whys: ["Our eyes see far things smaller, so drawings copy that.", "Converging lines tell the brain something goes far away.", "Overlapping shapes show which object is in front."] }),
  ],
  science: [
    L({ id: "cell", subject: "science", title: "Plant cells", blurb: "Wall, chloroplasts, vacuole.", pics: ["plant-cell"], videos: ["cell"],
      points: ["Cells are the tiny building blocks of living things", "Cell wall: stiff outer layer for shape and support", "Chloroplasts: make food from sunlight", "Vacuole: stores water and keeps the cell firm"],
      examples: ["Crunchy celery has cells full of water in their vacuoles. Wilted celery has lost that water.", "Leaves are green because cells hold many chloroplasts.", "The cell wall is like a cardboard box around a water balloon."],
      lab: { id: "cell", title: "Cell Explorer", intro: "Rotate the plant cell, click the parts, then play the find-it challenge." },
      intro: "Let's shrink down and explore a plant cell.", wrap: "Wall, chloroplasts, vacuole: three parts, three jobs.", homework: "Draw a plant cell and label the wall, chloroplasts and vacuole.",
      glossary: { "cell wall": "The cell wall is the strong outer layer that supports and protects a plant cell.", chloroplast: "Chloroplasts are the green structures where photosynthesis happens.", vacuole: "The vacuole is a large storage sac that holds water and nutrients.", photosynthesis: "Photosynthesis is how plants turn sunlight, water and carbon dioxide into sugar and oxygen.", chlorophyll: "Chlorophyll is the green pigment that captures sunlight.", nucleus: "The nucleus is the control center that holds the cell's DNA.", cell: "A cell is the smallest living building block of an organism.", mitochondria: "Mitochondria release energy from food for the cell to use." },
      whys: ["Plants need cell walls because they have no skeleton, so the walls hold them up.", "Chloroplasts matter because they turn sunlight into sugar.", "Vacuoles are big in plants because water pressure keeps stems standing."] }),
    L({ id: "photosynthesis", subject: "science", title: "Photosynthesis", blurb: "How plants make food.", pics: ["photosynthesis"], videos: ["photosynthesis"],
      points: ["Plants make their own food: photosynthesis", "Inputs: sunlight, water, carbon dioxide", "Outputs: sugar (food) and oxygen", "Chlorophyll in the chloroplasts captures the light"],
      examples: ["A plant on a sunny windowsill grows toward the light.", "Water goes up the roots, carbon dioxide comes in through the leaves.", "The oxygen we breathe is made by plants and algae."],
      lab: { id: "photosynth", title: "Grow the Plant", intro: "Give your plant sunlight, water and carbon dioxide in the right balance and grow it tall." },
      intro: "Today's question: how does a plant eat?", wrap: "Sunlight, water, air in. Sugar and oxygen out.", homework: "Observe a plant for a week and record how it changes.",
      glossary: { photosynthesis: "Photosynthesis is how plants turn sunlight, water and carbon dioxide into sugar and oxygen.", chlorophyll: "Chlorophyll is the green pigment that captures sunlight.", glucose: "Glucose is the sugar plants make for energy.", oxygen: "Oxygen is the gas plants release that we breathe.", "carbon dioxide": "Carbon dioxide is the gas plants take in from the air." },
      whys: ["Plants can't hunt or eat, so they make food from light.", "Light is the energy that powers the reaction.", "Oxygen is a leftover the plant releases."] }),
    L({ id: "watercycle", subject: "science", title: "The water cycle", blurb: "Evaporation to rain.", pics: ["water-cycle"], videos: ["watercycle"],
      points: ["Evaporation: the sun turns water into vapor", "Condensation: vapor cools into clouds", "Precipitation: rain, snow or hail falls", "Collection: water gathers and the cycle repeats"],
      examples: ["Puddles disappear on a sunny day: evaporation.", "A cold glass 'sweats': condensation.", "Rivers carry rain back to the sea."],
      lab: { id: "cardsort", cfg: "watercycle", title: "Order the Cycle", intro: "Put the stages of the water cycle in order." },
      intro: "Water is always moving. Let's follow it.", wrap: "Evaporate, condense, precipitate, collect, repeat.", homework: "Draw the water cycle and label four stages.",
      glossary: { evaporation: "Evaporation is when liquid water warms up and becomes a gas called vapor.", condensation: "Condensation is when vapor cools into tiny droplets, forming clouds.", precipitation: "Precipitation is water falling from clouds as rain, snow, sleet or hail.", vapor: "Vapor is water in gas form.", cycle: "A cycle is a series of steps that repeats." },
      whys: ["The sun supplies the energy to lift water into the air.", "Cold air at height cools the vapor, so it condenses.", "Gravity pulls the heavy droplets down as rain."] }),
    L({ id: "gravity", subject: "science", title: "Gravity", blurb: "Why things fall and orbit.", pics: ["orbit"], videos: ["gravity"],
      points: ["Gravity is a force that pulls objects together", "Earth pulls everything toward its center", "More mass means a stronger pull", "Gravity keeps the Moon in orbit around Earth"],
      examples: ["An apple falls straight down.", "You'd weigh less on the Moon because it has less mass.", "Without gravity the Moon would fly off into space."],
      lab: { id: "gravity", title: "Drop Zone", intro: "Pick a planet and an object, predict which lands first, then drop them." },
      intro: "Why does everything fall down? Today we explore gravity.", wrap: "Gravity pulls everything with mass.", homework: "Drop three objects from the same height and record what happens.",
      glossary: { gravity: "Gravity is the force that pulls objects with mass toward each other.", mass: "Mass is how much matter is in an object.", orbit: "An orbit is the curved path one object takes around another.", weight: "Weight is how hard gravity pulls on an object.", force: "A force is a push or a pull." },
      whys: ["Earth is so massive that its pull is strong enough to keep us on the ground.", "Without a push sideways, objects fall straight down.", "The Moon moves sideways fast enough that it keeps missing Earth, which is an orbit."] }),
  ],
  history: [
    L({ id: "egypt", subject: "history", title: "Ancient Egypt: the pyramids", blurb: "Building a wonder.", pics: ["pyramid", "timeline"], videos: ["egypt"],
      points: ["Pyramids were royal tombs built about 4,500 years ago", "Workers moved stone on sledges and boats along the Nile", "Architects planned each layer carefully", "The Great Pyramid took about 20 years"],
      examples: ["Blocks floated down the Nile during the yearly flood.", "Ramps helped workers raise blocks higher.", "The Great Pyramid was the tallest structure for almost 4,000 years."],
      lab: { id: "pyramid", title: "Pyramid Builders", intro: "Click to place stone blocks layer by layer. Your classmates haul the blocks." },
      intro: "Today we travel to ancient Egypt to see how people built mountains of stone.", wrap: "Planning, teamwork and the Nile made it possible.", homework: "Draw a pyramid and label two ways workers moved the stone.",
      glossary: { pharaoh: "A pharaoh was the king or queen of ancient Egypt.", pyramid: "A pyramid is a huge stone tomb with triangular sides.", nile: "The Nile is the long river that gave Egypt water, food and a way to move stone.", sledge: "A sledge is a sled used to drag heavy loads.", architect: "An architect plans how a building will be built.", tomb: "A tomb is a place where a person is buried." },
      whys: ["The Nile was the highway of Egypt, so building near it made moving stone easier.", "Planning mattered because mistakes in huge blocks were costly.", "Pyramids were built to protect the pharaoh in the afterlife."] }),
    L({ id: "silkroad", subject: "history", title: "The Silk Road", blurb: "Trade and ideas.", pics: ["silk-map", "timeline"], videos: ["silkroad"],
      points: ["A network of trade routes linking Asia, the Middle East and Europe", "Silk, spices and paper traveled west", "Caravans of camels crossed deserts", "Ideas, religions and inventions traveled too"],
      examples: ["Silk was made only in China at first.", "Paper-making spread west along the routes.", "Oasis towns grew rich from trade."],
      lab: { id: "cardsort", cfg: "silkroad", title: "Trade Match", intro: "Send each good to the city where it was famous." },
      intro: "Today: the Silk Road, history's great trading highway.", wrap: "Trade moves goods and ideas.", homework: "List three things traded and where each came from.",
      glossary: { caravan: "A caravan is a group of traders traveling together, often with camels.", oasis: "An oasis is a place in the desert with water.", trade: "Trade is exchanging goods or services.", silk: "Silk is a smooth fabric made from silkworm threads.", route: "A route is a path from one place to another." },
      whys: ["Silk was rare and valuable, so people traveled far to trade for it.", "Camels can go long distances without water.", "When people meet to trade, they also share ideas."] }),
    L({ id: "printing", subject: "history", title: "The printing press", blurb: "Books for everyone.", pics: ["press", "timeline"], videos: ["printing"],
      points: ["Before 1440, books were copied by hand", "Gutenberg built a press with movable metal letters", "Letters could be rearranged and reused", "Books got cheaper and more people learned to read"],
      examples: ["A monk could spend months copying one Bible.", "A press could print hundreds of pages a day.", "News and new ideas spread across Europe faster."],
      lab: { id: "press", title: "Set the Type", intro: "Pick letters from the tray to spell each word, then pull the lever to print." },
      intro: "Today we meet the invention that changed how ideas travel.", wrap: "Movable type made knowledge cheaper and faster to share.", homework: "Explain in two sentences how the press changed reading.",
      glossary: { press: "A printing press stamps ink from letters onto paper.", "movable type": "Movable type is letters that can be rearranged and reused.", gutenberg: "Johannes Gutenberg built the first European movable-type press around 1440.", scribe: "A scribe copied books by hand.", manuscript: "A manuscript is a handwritten book." },
      whys: ["Reusing letters made printing far faster than hand copying.", "Cheaper books meant more people could learn to read.", "Faster printing helped ideas spread."] }),
    L({ id: "teaparty", subject: "history", title: "The Boston Tea Party", blurb: "A protest about taxes.", pics: ["timeline"], videos: ["teaparty"],
      points: ["1773: colonists were taxed without a vote", "'No taxation without representation'", "Colonists threw 342 chests of tea into Boston Harbor", "It helped push the colonies toward revolution"],
      examples: ["The tax stayed on tea even though the price was low.", "The protest was at night so colonists could act quickly.", "Britain answered with harsh laws, which angered more colonists."],
      lab: { id: "cardsort", cfg: "teaparty", title: "Build the Timeline", intro: "Put the events leading to the Revolution in order." },
      intro: "Today: a night in Boston harbor that changed history.", wrap: "A protest about fairness helped start a country.", homework: "Write two sentences: why were colonists angry?",
      glossary: { colonist: "A colonist is a person who lives in a colony.", tax: "A tax is money people must pay to the government.", representation: "Representation means having people who speak and vote for you in government.", protest: "A protest is a public way to show disagreement.", revolution: "A revolution is a big change in government, often by force." },
      whys: ["Colonists felt it was unfair to be taxed with no say in the decision.", "Dumping the tea made a loud statement against the tax.", "Britain's response pushed more colonists to side with the protesters."] }),
    L({ id: "bill", subject: "history", title: "Government: how a bill becomes a law", blurb: "From idea to law.", pics: ["bill-flow"], videos: ["bill"],
      points: ["It starts with an idea from a citizen", "A member of Congress introduces a bill", "Committees study it, then the House and Senate vote", "The President signs it into law or vetoes it"],
      examples: ["A town wants a crosswalk. A representative writes a bill.", "Both the House and Senate must pass the same bill.", "If the President vetoes, Congress can override with a big vote."],
      lab: { id: "cardsort", cfg: "bill", title: "Bill to Law", intro: "Put the steps in order so the bill becomes a law." },
      intro: "Today: how an idea becomes a law.", wrap: "Idea, bill, committee, vote, signature.", homework: "Pick a rule you'd like in school and list the steps to make it a law.",
      glossary: { bill: "A bill is a proposed law.", congress: "Congress is the part of government that makes laws: the House and the Senate.", veto: "A veto is when the President refuses to sign a bill.", committee: "A committee is a small group that studies a bill.", law: "A law is a rule that everyone must follow.", amendment: "An amendment is a change or addition." },
      whys: ["Many steps keep a law from passing without careful thought.", "Two chambers means more voices check the idea.", "The President's signature is the last check."] }),
    L({ id: "branches", subject: "history", title: "Government: three branches", blurb: "Checks and balances.", pics: ["branches"], videos: ["branches"],
      points: ["Legislative (Congress): makes laws", "Executive (President): carries out laws", "Judicial (courts): decide what laws mean", "Checks and balances: each branch limits the others"],
      examples: ["Congress writes a law. The President signs it. Courts can say if it follows the Constitution.", "The President can veto. Congress can override.", "The Senate approves judges the President picks."],
      lab: { id: "cardsort", cfg: "branches", title: "Branch Sort", intro: "Drag each job to the branch that does it." },
      intro: "Today: why no one person holds all the power.", wrap: "Three branches keep power balanced.", homework: "Match five jobs to the right branch.",
      glossary: { legislative: "The legislative branch, Congress, makes laws.", executive: "The executive branch, led by the President, carries out laws.", judicial: "The judicial branch, the courts, decides what laws mean.", constitution: "The Constitution is the set of rules for how the government works.", "checks and balances": "Checks and balances let each branch limit the power of the others." },
      whys: ["Splitting power prevents any one person from becoming too strong.", "Each branch can check the others, so mistakes can be fixed.", "The Constitution spells out each branch's job."] }),
    L({ id: "election", subject: "history", title: "Government: election day", blurb: "How voting works.", pics: ["bill-flow"], videos: ["election"],
      points: ["Citizens vote to choose leaders", "A ballot is secret so people vote freely", "Votes are counted by officials", "The candidate with the most votes wins"],
      examples: ["A class votes for a class pet.", "A mayor wins by getting the most votes.", "Every vote counts, even in close elections."],
      lab: { id: "vote", title: "Class Vote", intro: "Cast your vote for the class pet and see how your classmates vote." },
      intro: "Today: how a community makes a decision by voting.", wrap: "Voting gives everyone a say.", homework: "Ask three people what they'd vote for and tally the answers.",
      glossary: { ballot: "A ballot is the paper or screen where you mark your vote.", candidate: "A candidate is a person running for an office.", election: "An election is when people vote to choose leaders.", majority: "A majority is more than half of the votes.", poll: "A poll is where people vote, or a survey of opinions." },
      whys: ["Secret ballots let people vote without pressure.", "Counting every vote keeps the result fair.", "Voting lets citizens help decide how they are governed."] }),
  ],
  careers: [
    L({ id: "find", subject: "careers", title: "Finding your path", blurb: "Interests, skills and values.", pics: ["career-path"], videos: [],
      points: ["Interests: what you enjoy doing", "Skills: what you can do well, and can learn", "Values: what matters to you, like helping, creating or earning", "The best fit sits where all three overlap"],
      examples: ["Enjoys fixing bikes (interest), patient with details (skill), likes seeing things work (value): mechanic, engineer or technician.", "Loves explaining things (interest), clear speaker (skill), wants to help others grow (value): teacher or trainer.", "Likes animals, calm under pressure, wants to care for living things: veterinary technician."],
      lab: { id: "cardsort", cfg: "careers-find", title: "Interests, Skills, Values", intro: "Sort each statement into Interests, Skills or Values." },
      intro: "Today in CarryingCareers: finding the path that fits you. Every career, of every type, starts with knowing yourself.", wrap: "Interests, skills and values all point somewhere. Keep exploring.", homework: "Write one interest, one skill and one value you have.",
      glossary: { "interest": "An interest is something you enjoy doing or learning about.", "skill": "A skill is something you can do well. Skills can be learned and practiced.", "value": "A value is something that matters to you, like helping others, creativity or security.", "career": "A career is the work you do over many years, often growing from job to job.", "strength": "A strength is something you are naturally good at." },
      whys: ["Careers fit better when they match what you enjoy, what you are good at, and what you care about.", "Skills can be learned, so you do not need to be great at everything today.", "Values matter because a job that fits them feels meaningful, not only paid."] }),
    L({ id: "build", subject: "careers", title: "Building and moving things", blurb: "Construction, manufacturing, transportation.", pics: ["career-clusters"], videos: [],
      points: ["Architecture and Construction: designing and building homes, roads and bridges", "Manufacturing: making products in factories, from cars to cookies", "Transportation, Distribution and Logistics: moving people and goods by road, rail, air and sea", "Many of these careers use skilled trades, with paid training on the job"],
      examples: ["Electrician, carpenter, plumber and architect all work on the buildings we use.", "A welder or machinist helps make everything from bicycles to airplane parts.", "Pilots, truck drivers, ship captains and warehouse coordinators keep goods moving."],
      lab: { id: "cardsort", cfg: "careers-build", title: "Match the job", intro: "Sort each job into its career cluster." },
      intro: "Today: careers that build things and move them from place to place.", wrap: "These clusters keep our world built and delivered.", homework: "Name one thing you used today and list who helped build or deliver it.",
      glossary: { "trade": "A trade is a skilled job learned by training and practice, like plumbing or welding.", "apprentice": "An apprentice learns a trade while working and earning pay.", "logistics": "Logistics is planning how goods are stored and moved.", "manufacturing": "Manufacturing means making products, often with machines.", "architect": "An architect designs buildings." },
      whys: ["Trades are in demand because buildings and machines always need people to make and fix them.", "Logistics matters because nothing reaches a store or home without being moved.", "Apprenticeships let people earn while they learn."] }),
    L({ id: "care", subject: "careers", title: "Caring, teaching and helping", blurb: "Health, education and human services.", pics: ["career-clusters"], videos: [],
      points: ["Health Science: keeping people well, from nurses to lab technicians", "Education and Training: teaching and coaching at every age", "Human Services: counselors, social workers and child care workers who support families", "These careers need people skills such as listening and patience"],
      examples: ["Nurse, dentist, paramedic and physical therapist are Health Science careers.", "Teacher, librarian, tutor and swim coach all work in Education and Training.", "A school counselor or social worker helps people through hard times."],
      lab: { id: "cardsort", cfg: "careers-care", title: "Who helps whom", intro: "Sort each job into its career cluster." },
      intro: "Today: careers where the work is helping people learn, heal and grow.", wrap: "Helping careers grow because people always need care and learning.", homework: "Interview someone who helps others in their work and ask what they enjoy most.",
      glossary: { "nurse": "A nurse cares for patients and works with doctors.", "counselor": "A counselor listens and helps people make plans and solve problems.", "therapist": "A therapist helps people recover or feel better, in body or mind.", "education": "Education careers help people learn.", "patience": "Patience is staying calm while something takes time." },
      whys: ["People skills matter because these jobs are about people, not only tasks.", "Training varies, from short certificates to many years of study.", "These careers are steady because every community needs health and learning."] }),
    L({ id: "public", subject: "careers", title: "Safety, law and government", blurb: "Public safety, law and public service.", pics: ["career-clusters"], videos: [],
      points: ["Law, Public Safety, Corrections and Security: protecting people and keeping rules fair", "Government and Public Administration: running towns, states and the country", "Careers include firefighter, police officer, paralegal, judge and city planner", "Public service means working for the community"],
      examples: ["Firefighters and emergency medical workers respond when someone needs help fast.", "A paralegal helps lawyers research and prepare cases.", "A city planner decides where roads, parks and homes can go."],
      lab: { id: "cardsort", cfg: "careers-public", title: "Public service sort", intro: "Sort each job into its cluster." },
      intro: "Today: careers that protect people and run our communities.", wrap: "Public careers keep communities safe and fair.", homework: "Find one public service in your town and write what it does.",
      glossary: { "public": "Public means belonging to or serving everyone in a community.", "paralegal": "A paralegal assists lawyers with research and paperwork.", "planner": "A city planner decides how land and buildings are used.", "security": "Security means keeping people and places safe.", "law": "Law is the set of rules a community agrees to follow." },
      whys: ["Public service careers keep communities safe and orderly.", "Many need training, tests or a degree because the work carries big responsibility.", "Planners and officials shape daily life, from roads to parks."] }),
    L({ id: "tech", subject: "careers", title: "Technology, science and engineering", blurb: "IT and STEM careers.", pics: ["career-clusters"], videos: [],
      points: ["Information Technology: building software, networks and keeping data safe", "Science, Technology, Engineering and Math (STEM): solving problems with research and design", "Careers include web developer, network administrator, chemist, civil engineer and data analyst", "Tools change fast, so these careers reward learning new skills"],
      examples: ["A web developer builds the pages and apps people use every day.", "A civil engineer designs bridges and water systems.", "A data analyst finds patterns in numbers to help people decide."],
      lab: { id: "cardsort", cfg: "careers-tech", title: "Tech and STEM sort", intro: "Sort each job into IT or STEM." },
      intro: "Today: careers that build digital tools and solve science and engineering problems.", wrap: "Technology and science careers keep changing, so keep learning.", homework: "Pick one tech or science job and write a problem it solves.",
      glossary: { "engineer": "An engineer designs and builds solutions to problems.", "developer": "A developer writes software.", "data": "Data is information, often numbers, that can be studied for patterns.", "stem": "STEM stands for science, technology, engineering and math.", "network": "A network connects computers so they can share information." },
      whys: ["STEM careers solve real problems, like clean water and safe bridges.", "Technology changes fast, so learning never stops.", "Math and logic are useful in many different careers."] }),
    L({ id: "business", subject: "careers", title: "Business, money and sales", blurb: "Business, finance and marketing.", pics: ["career-clusters"], videos: [],
      points: ["Business Management and Administration: organizing people, plans and offices", "Finance: banking, accounting and investing", "Marketing, Sales and Service: helping people learn about and buy products", "Entrepreneurs start their own businesses"],
      examples: ["An office manager keeps a team running smoothly.", "An accountant tracks money and prepares taxes.", "A sales representative explains products and helps customers choose."],
      lab: { id: "cardsort", cfg: "careers-biz", title: "Business sort", intro: "Sort each job into its cluster." },
      intro: "Today: careers in business, money and sales.", wrap: "Business careers need organizing, numbers and communication.", homework: "Sketch a small business idea and who your customers would be.",
      glossary: { "entrepreneur": "An entrepreneur starts and runs a business.", "accountant": "An accountant records and checks money.", "marketing": "Marketing is how a business tells people about its products.", "customer": "A customer is a person who buys a product or service.", "profit": "Profit is the money left after costs are paid." },
      whys: ["Businesses need people who can plan, count and communicate.", "Entrepreneurs take risks to create something new.", "Finance keeps money safe and growing."] }),
    L({ id: "create", subject: "careers", title: "Arts, media and hospitality", blurb: "Creative careers, travel and food.", pics: ["career-clusters"], videos: [],
      points: ["Arts, A/V Technology and Communications: design, film, music, writing and broadcasting", "Hospitality and Tourism: hotels, restaurants, events and travel", "Careers include graphic designer, journalist, chef, hotel manager and event planner", "Creative careers often start with a portfolio of your work"],
      examples: ["A graphic designer makes logos, posters and websites.", "A journalist researches and reports the news.", "A chef or hotel manager makes guests feel welcome."],
      lab: { id: "cardsort", cfg: "careers-create", title: "Creative sort", intro: "Sort each job into its cluster." },
      intro: "Today: careers in creativity, communication and welcoming people.", wrap: "Creative and service careers share one thing: they make people's day better.", homework: "Start a portfolio page: write down three pieces of work you are proud of.",
      glossary: { "portfolio": "A portfolio is a collection of your best work to show others.", "designer": "A designer plans how something will look and work.", "journalist": "A journalist gathers facts and reports them.", "hospitality": "Hospitality means welcoming and caring for guests.", "tourism": "Tourism is travel for fun or discovery." },
      whys: ["A portfolio proves your skill better than words.", "Creative jobs can be competitive, so practice and projects matter.", "Hospitality teaches teamwork and calm under pressure."] }),
    L({ id: "land", subject: "careers", title: "Food, farms and nature", blurb: "Agriculture, food and natural resources.", pics: ["career-clusters"], videos: [],
      points: ["Agriculture, Food and Natural Resources: growing food, caring for animals and protecting the land", "Careers include farmer, veterinary technician, park ranger, forester and food scientist", "Technology like drones and sensors is changing farming", "These careers often mix outdoor work with science"],
      examples: ["A farmer plans crops, soil and water through the seasons.", "A park ranger protects wildlife and helps visitors.", "A food scientist tests how to make food safe and tasty."],
      lab: { id: "cardsort", cfg: "careers-land", title: "Land and food sort", intro: "Sort each job into its group." },
      intro: "Today: careers that grow our food and protect our natural world.", wrap: "Everyone depends on food, water and land, so these careers matter.", homework: "Trace one meal back to the farm: list every job it passed through.",
      glossary: { "agriculture": "Agriculture is farming: growing crops and raising animals.", "forester": "A forester manages forests.", "ranger": "A park ranger protects parks and wildlife.", "sustainable": "Sustainable means meeting needs without using up resources for the future.", "veterinary": "Veterinary means caring for animal health." },
      whys: ["Food, water and land are needs for everyone, so the work is always needed.", "Science helps farming use less water and protect soil.", "Outdoor careers protect nature for the future."] }),
    L({ id: "plan", subject: "careers", title: "Making a plan", blurb: "Skills, resume and interview.", pics: ["career-path"], videos: [],
      points: ["Explore first, then research what jobs need", "Choose a training route: school, trade, certificate, apprenticeship, military or work", "Build a resume: a one-page summary of your skills and experience", "Practice interviews: greet, listen, answer clearly and ask a question"],
      examples: ["Resume line: 'Organized a school fundraiser and raised 200 dollars.'", "Interview tip: answer with a short story that shows a skill.", "Follow-up: send a thank-you note within a day."],
      lab: { id: "cardsort", cfg: "careers-plan", title: "Steps in order", intro: "Put the steps of a career plan in order." },
      intro: "Today: turning an idea into a plan you can start now.", wrap: "A plan makes a big goal feel doable. Take the next step.", homework: "Draft a five-line resume with a skill, a project and a goal.",
      glossary: { "resume": "A resume is a short page listing your skills, experience and goals.", "interview": "An interview is a conversation where an employer learns about you.", "certificate": "A certificate shows you finished training or passed a test.", "internship": "An internship is short-term work to learn on the job.", "network": "To network is to meet people who can share advice and opportunities." },
      whys: ["A plan turns a big dream into small steps.", "A resume helps an employer see your skills fast.", "Practice makes interviews less scary."] }),
    L({ id: "money", subject: "careers", title: "Pay, paths and choices", blurb: "Money basics and training routes.", pics: ["pay-paths"], videos: [],
      points: ["Gross pay is before taxes; net pay is what you take home", "Training routes: certificate, trade school, apprenticeship, college, military or entering work directly", "Compare careers by daily tasks, pay, training time and chance to grow", "Budget: spend less than you earn, and save for goals"],
      examples: ["An apprenticeship pays you while you learn, often for three to five years.", "A certificate can take months, a bachelor's degree about four years.", "Net pay is smaller than gross pay because of taxes and deductions."],
      lab: { id: "cardsort", cfg: "careers-money", title: "Money in, money out", intro: "Sort each item into Pay (money in) or Costs (money out)." },
      intro: "Today: understanding pay and choosing a route that works for you.", wrap: "There are many roads to a good career. Compare before you choose.", homework: "Compare two careers: tasks, training time and pay.",
      glossary: { "gross": "Gross pay is what you earn before taxes.", "net": "Net pay is what you take home after taxes and deductions.", "budget": "A budget is a plan for spending and saving money.", "apprenticeship": "An apprenticeship is paid on-the-job training combined with classes.", "salary": "A salary is fixed pay for a year of work." },
      whys: ["Comparing helps you choose with facts, not just guesses.", "Net pay matters because it is the money you can actually spend.", "Many routes lead to good careers, not just one."] }),
  ],
  life: [
    L({ id: "money", subject: "life", title: "Earning, spending and saving", blurb: "Needs, wants and saving.", pics: ["life-wheel"], videos: [],
      points: ["Income is money you earn; expenses are money you spend", "Needs come first (food, home, health), wants come next", "Pay yourself first: set aside part of everything you get", "Small amounts saved often grow into big ones"],
      examples: ["Needs: groceries, rent, medicine. Wants: games, snacks, new shoes.", "Save 10 out of every 100 you receive and after ten rounds you have 100 saved.", "Before a big purchase, wait one day. If you still want it, then decide."],
      lab: { id: "cardsort", cfg: "life-money", title: "Needs, wants, savings", intro: "Sort each item into Needs, Wants or Savings." },
      intro: "Today in Life Lessons: the money basics every independent person uses.", wrap: "Needs first, then wants, and always a little for the future.", homework: "List three needs, three wants and one thing you could save for.",
      glossary: { "income": "Income is money you receive, like pay or allowance.", "expense": "An expense is money you spend.", "need": "A need is something you must have to live and stay healthy.", "want": "A want is something nice to have but not necessary.", "savings": "Savings is money you set aside for later." },
      whys: ["Needs come first because they keep you healthy and housed.", "Paying yourself first makes saving automatic instead of leftover.", "Waiting a day stops impulse buys."] }),
    L({ id: "budget", subject: "life", title: "Budgets: where your money goes", blurb: "The 50/30/20 plan.", pics: ["budget-split"], videos: [],
      points: ["A budget is a plan for every dollar before you spend it", "A simple guide: about 50% needs, 30% wants, 20% savings and debt", "Track spending for a month to see where money really goes", "Review and adjust: a budget is a living plan"],
      examples: ["Earn 1000: about 500 for needs, 300 for wants, 200 for savings or paying debt.", "Streaming, eating out and games are wants you can trim first.", "If rent is more than half your income, look for ways to lower other costs or raise income."],
      lab: { id: "cardsort", cfg: "life-budget", title: "Budget sort", intro: "Sort each item into its part of the budget." },
      intro: "Today: building a budget you can actually follow.", wrap: "A budget is not a punishment. It is a plan that gives your money a job.", homework: "Track everything you spend for three days and sort it into needs, wants and savings.",
      glossary: { "budget": "A budget is a plan for how you will spend and save money.", "rent": "Rent is money paid regularly to live in a home you do not own.", "debt": "Debt is money you owe.", "emergency": "An emergency fund is savings kept for surprises like a repair or a medical bill.", "track": "To track spending is to write down what you buy." },
      whys: ["Planning first stops money from disappearing.", "The 50/30/20 split is a guide, not a law: adjust it to your life.", "Tracking shows habits you did not notice."] }),
    L({ id: "credit", subject: "life", title: "Credit, debt and scams", blurb: "Borrowing wisely and spotting scams.", pics: ["life-wheel"], videos: [],
      points: ["Credit lets you borrow now and pay later, with interest", "A credit score shows lenders how reliably you repay", "Pay on time and keep balances low to build good credit", "Scams rush you and ask for odd payments: slow down and verify"],
      examples: ["Paying only the minimum on a card means interest keeps growing.", "A text says you won a prize if you pay a fee: that is a scam.", "Never share passwords, PINs or one-time codes with someone who contacts you first."],
      lab: { id: "cardsort", cfg: "life-credit", title: "Safe or scam", intro: "Sort each item into Safe habit or Warning sign." },
      intro: "Today: how borrowing works and how to spot a scam.", wrap: "Borrow carefully, pay on time and slow down when someone rushes you.", homework: "Write three warning signs of a scam and who you would tell.",
      glossary: { "credit": "Credit is the ability to borrow money and pay it back later.", "interest": "Interest is the extra money you pay for borrowing.", "score": "A credit score is a number that shows how reliably you repay.", "scam": "A scam is a trick to take your money or information.", "phishing": "Phishing is a fake message pretending to be someone you trust." },
      whys: ["Interest means borrowing costs more than the amount you borrowed.", "A good score can lower the cost of borrowing later.", "Scammers rely on speed and fear, so slowing down beats them."] }),
    L({ id: "home", subject: "life", title: "Keeping a home", blurb: "Cleaning, laundry and basic care.", pics: ["life-wheel"], videos: [],
      points: ["Daily habits beat big clean-ups: dishes, trash, tidy", "Sort laundry by color and fabric, and read the care label", "Clean from top to bottom and from cleanest to dirtiest", "Know where the water shut-off and fuse box are"],
      examples: ["Wash dishes soon after eating so food does not harden.", "A red sock in a white wash can turn everything pink.", "If a pipe leaks, turn off the water at the shut-off, then call for help."],
      lab: { id: "cardsort", cfg: "life-home", title: "Laundry steps", intro: "Put the laundry steps in order." },
      intro: "Today: keeping a home running smoothly.", wrap: "A little each day keeps a home comfortable.", homework: "Do one household task fully this week and note how long it took.",
      glossary: { "laundry": "Laundry is clothes and linens that need washing.", "label": "A care label tells how to wash and dry an item.", "shutoff": "A shut-off valve stops water flowing to a pipe or the whole home.", "routine": "A routine is something you do regularly.", "detergent": "Detergent is soap for washing clothes." },
      whys: ["Daily habits are easier than rescuing a huge mess.", "Care labels prevent shrunk or ruined clothes.", "Knowing the shut-off limits damage in a leak."] }),
    L({ id: "food", subject: "life", title: "Cooking and food safety", blurb: "Safe, simple meals.", pics: ["life-wheel"], videos: [],
      points: ["Wash hands for 20 seconds before cooking", "Keep raw meat away from ready-to-eat food", "Cook to a safe temperature and chill leftovers within two hours", "A plate with vegetables, protein and grains keeps energy steady"],
      examples: ["Use one cutting board for raw chicken and another for vegetables.", "Soup left on the counter all night should be thrown away.", "Eggs, rice and vegetables make a cheap, balanced meal."],
      lab: { id: "cardsort", cfg: "life-food", title: "Do and don't", intro: "Sort each habit into Do or Don't." },
      intro: "Today: cooking simple meals safely.", wrap: "Clean hands, clean boards and the right temperature keep meals safe.", homework: "Plan three simple meals and a shopping list for them.",
      glossary: { "nutrition": "Nutrition is how food helps your body grow and work.", "bacteria": "Bacteria are tiny living things; some can make you sick.", "leftovers": "Leftovers are cooked food saved for another meal.", "thermometer": "A food thermometer checks if food is cooked enough.", "protein": "Protein helps build and repair the body." },
      whys: ["Handwashing removes germs before they reach food.", "Cold slows bacteria, so chilling leftovers matters.", "A balanced plate gives steady energy."] }),
    L({ id: "health", subject: "life", title: "Health, sleep and getting care", blurb: "Taking care of your body and the system around it.", pics: ["life-wheel"], videos: [],
      points: ["Sleep, movement and water are the basics of health", "Know your own medicines and your family health history", "Make appointments ahead and write down your questions", "Insurance has a premium, a deductible and copays: read what yours covers"],
      examples: ["Teens usually need about 8 to 10 hours of sleep.", "Before a doctor visit write: what hurts, since when, what helps.", "A copay is a set fee you pay at a visit; a deductible is what you pay before insurance helps more."],
      lab: { id: "cardsort", cfg: "life-health", title: "How urgent is it?", intro: "Sort each situation into the right level of care." },
      intro: "Today: looking after your health and finding care when you need it.", wrap: "Small habits keep you well, and knowing where to go keeps you safe.", homework: "Write your doctor's name, your emergency contact and one health habit to improve.",
      glossary: { "insurance": "Health insurance helps pay for medical care.", "deductible": "A deductible is what you pay before insurance pays more.", "copay": "A copay is a fixed fee you pay for a visit or medicine.", "pharmacy": "A pharmacy fills prescriptions and answers medicine questions.", "symptom": "A symptom is a sign something may be wrong in your body." },
      whys: ["Sleep helps your body repair and your mind learn.", "Writing questions down means you remember them in the room.", "Knowing your coverage prevents surprise bills."] }),
    L({ id: "mind", subject: "life", title: "Feelings, stress and asking for help", blurb: "Looking after your mind.", pics: ["life-wheel"], videos: [],
      points: ["All feelings are information; none are bad", "Stress is normal; breathing, movement and sleep help", "Talking to someone you trust makes problems smaller", "If you feel unsafe or hopeless, tell a trusted adult right away or call or text a crisis line such as 988 in the US"],
      examples: ["Name the feeling: 'I feel nervous about the test.' Naming it makes it easier to handle.", "Try breathing in for four counts and out for six.", "Asking for help is a strength: coaches, counselors and friends are there for it."],
      lab: { id: "cardsort", cfg: "life-mind", title: "Helpful or unhelpful", intro: "Sort each response to stress." },
      intro: "Today: understanding feelings and when to ask for help.", wrap: "You do not have to carry hard things alone.", homework: "Write two things that help you calm down and one person you can talk to.",
      glossary: { "stress": "Stress is the body's reaction to pressure or change.", "anxiety": "Anxiety is strong worry or fear that is hard to switch off.", "coping": "Coping is the way you handle hard feelings or situations.", "boundary": "A boundary is a limit that protects your wellbeing.", "counselor": "A counselor is a trained person who helps with feelings and problems." },
      whys: ["Naming feelings reduces their power.", "Breathing slowly calms the body's alarm.", "Support makes hard things lighter."] }),
    L({ id: "safety", subject: "life", title: "Staying safe: first aid and emergencies", blurb: "Know what to do.", pics: ["first-aid"], videos: [],
      points: ["In an emergency call 911 (or your local number) and stay calm", "Know two exits from every place and a family meeting spot", "For a small burn, cool it under cool running water for several minutes", "Keep a first aid kit and know where it is"],
      examples: ["Tell the operator where you are first, then what happened.", "Pressure with a clean cloth helps slow bleeding from a cut while you get help.", "Smoke alarms need new batteries and a test every month."],
      lab: { id: "cardsort", cfg: "life-safety", title: "Emergency steps", intro: "Put the emergency steps in order." },
      intro: "Today: staying calm and safe when something goes wrong.", wrap: "Practice makes calm. Plan now and you will think more clearly later.", homework: "Find your home's two exits and agree on a meeting spot.",
      glossary: { "emergency": "An emergency is a sudden situation needing immediate help.", "dispatcher": "A dispatcher answers emergency calls and sends help.", "firstaid": "First aid is basic help given before professionals arrive.", "evacuate": "To evacuate is to leave a dangerous place quickly and safely.", "kit": "A first aid kit holds bandages and basic supplies." },
      whys: ["Calm helps you give clear information.", "Planning exits saves time when seconds matter.", "Cooling a burn limits damage."] }),
    L({ id: "digital", subject: "life", title: "Digital safety and privacy", blurb: "Staying safe online.", pics: ["life-wheel"], videos: [],
      points: ["Use long, different passwords or a password manager", "Turn on two-step sign-in for important accounts", "Think before you post: the internet remembers", "Do not click unexpected links or share one-time codes"],
      examples: ["A passphrase of four random words is long and easy to remember.", "A friend's account suddenly asks for money: call them to check.", "Private information includes your address, school and birthdate."],
      lab: { id: "cardsort", cfg: "life-digital", title: "Strong or risky", intro: "Sort each habit into Strong habit or Risky habit." },
      intro: "Today: protecting your accounts and your privacy.", wrap: "A few habits protect most of your digital life.", homework: "Turn on two-step sign-in for one account and change one weak password.",
      glossary: { "password": "A password is a secret code that protects an account.", "privacy": "Privacy is control over who knows things about you.", "twostep": "Two-step sign-in asks for a second proof, like a code, after your password.", "footprint": "A digital footprint is the trail of what you do and post online.", "malware": "Malware is harmful software." },
      whys: ["Unique passwords stop one leak from opening everything.", "A second step blocks most account break-ins.", "Posts can be copied, so think first."] }),
    L({ id: "people", subject: "life", title: "Relationships, boundaries and consent", blurb: "Respect in every relationship.", pics: ["life-wheel"], videos: [],
      points: ["Healthy relationships feel respectful, safe and equal", "Consent is a clear, freely given yes, and anyone can change their mind", "You can say no kindly and firmly, and accept someone else's no", "Trusted adults, friends and counselors can help when something feels wrong"],
      examples: ["A good friend asks before borrowing and thanks you after.", "If someone says no or seems unsure, stop and respect it.", "If a relationship makes you afraid or controlled, tell a trusted adult."],
      lab: { id: "cardsort", cfg: "life-people", title: "Respectful or not", intro: "Sort each behavior." },
      intro: "Today: respect, boundaries and consent.", wrap: "Respect goes both ways.", homework: "Write one boundary you have and a kind way to say it.",
      glossary: { "boundary": "A boundary is a limit you set for how you want to be treated.", "consent": "Consent is freely given permission, and it can be taken back.", "respect": "Respect means treating others as they deserve.", "assertive": "Being assertive is saying what you need clearly and kindly.", "trust": "Trust is believing someone will be honest and safe." },
      whys: ["Respect keeps everyone safe and valued.", "Consent can change at any time, so check in.", "Asking for help is part of staying safe."] }),
    L({ id: "time", subject: "life", title: "Time, goals and organization", blurb: "Planning your days.", pics: ["life-wheel"], videos: [],
      points: ["Write goals as small steps with dates", "Sort tasks into urgent and important", "Use one calendar and one to-do list", "Rest is part of the plan: schedule breaks"],
      examples: ["Goal: save 200. Steps: save 20 a week for ten weeks.", "Homework due tomorrow is urgent and important; sorting your closet is neither.", "A short break every hour keeps focus fresh."],
      lab: { id: "cardsort", cfg: "life-time", title: "Goal steps", intro: "Put the goal-setting steps in order." },
      intro: "Today: making a plan and sticking to it.", wrap: "Small steps on a calendar beat big plans in your head.", homework: "Write one goal, three steps and put the first step on your calendar.",
      glossary: { "goal": "A goal is something you want to achieve.", "priority": "A priority is something that matters most right now.", "deadline": "A deadline is the date something must be done.", "procrastinate": "To procrastinate is to put off something you need to do.", "habit": "A habit is something you do automatically." },
      whys: ["Small steps make big goals feel doable.", "Sorting by urgent and important protects your time.", "Breaks keep you from burning out."] }),
    L({ id: "adult", subject: "life", title: "Adult paperwork", blurb: "IDs, taxes, renting and voting.", pics: ["life-wheel"], videos: [],
      points: ["Keep your birth certificate, Social Security card and passport locked at home", "Taxes: employers withhold pay, and many people file a return each year", "Renting: read the lease, the deposit and who fixes what", "Citizens can register to vote: every election is a chance to have a say"],
      examples: ["Carry a photo ID, not your Social Security card.", "A security deposit is money held in case of damage and is usually returned.", "Register to vote early and check the dates for your area."],
      lab: { id: "cardsort", cfg: "life-adult", title: "Lock up or carry", intro: "Sort each item into where it belongs." },
      intro: "Today: the paperwork of becoming an adult in the US.", wrap: "Know what you have, keep it safe and read before you sign.", homework: "List your important documents and where each is kept.",
      glossary: { "lease": "A lease is a contract to rent a home.", "deposit": "A deposit is money held until you leave a rental in good shape.", "tax": "A tax is money paid to the government for public services.", "register": "To register is to sign up, for example to vote.", "contract": "A contract is a written agreement." },
      whys: ["Important papers are hard to replace, so lock them up.", "Reading the lease prevents surprises.", "Voting is how citizens choose leaders."] }),
    L({ id: "travel", subject: "life", title: "Getting around", blurb: "Maps, transit and car basics.", pics: ["life-wheel"], videos: [],
      points: ["Read a map or app: starting point, destination and time", "Check the schedule and always have a backup plan", "Share your plan with someone you trust", "Cars need insurance, fuel and checks like tire pressure"],
      examples: ["Leave ten minutes early so a late bus does not make you late.", "Charge your phone and carry fare before a trip.", "Check tire pressure and fuel before a long drive."],
      lab: { id: "cardsort", cfg: "life-travel", title: "Plan a trip", intro: "Put the trip planning steps in order." },
      intro: "Today: getting from place to place safely.", wrap: "Plan, tell someone and leave early.", homework: "Plan a trip across town: route, time, cost and backup.",
      glossary: { "route": "A route is the path you take to get somewhere.", "transit": "Transit is public transportation like buses and trains.", "fare": "A fare is the price of a ride.", "insurance": "Car insurance helps pay if there is an accident.", "navigate": "To navigate is to find your way." },
      whys: ["Backup plans help when things change.", "Telling someone keeps you safe.", "Basic checks prevent breakdowns."] }),
    L({ id: "decide", subject: "life", title: "Solving problems and deciding", blurb: "A simple way to choose.", pics: ["life-wheel"], videos: [],
      points: ["Name the problem clearly", "List your options and what each could cost or gain", "Ask someone you trust and look up facts", "Decide, act, then check how it went and learn"],
      examples: ["Problem: I can't afford a phone. Options: save, buy used, wait.", "Compare options on cost, time and risk.", "If a choice did not work, you still learned something for next time."],
      lab: { id: "cardsort", cfg: "life-decide", title: "Decision steps", intro: "Put the decision steps in order." },
      intro: "Today: a repeatable way to solve problems.", wrap: "Good decisions are a skill you can practice.", homework: "Pick a real choice you face and write your options and what each costs.",
      glossary: { "problem": "A problem is something that needs a solution.", "option": "An option is a choice you could make.", "tradeoff": "A tradeoff is giving up one thing to get another.", "risk": "Risk is the chance something goes wrong.", "reflect": "To reflect is to think about what happened and what you learned." },
      whys: ["Naming the problem keeps you from solving the wrong one.", "Comparing options shows tradeoffs.", "Checking results turns mistakes into learning."] }),
  ],
};
export const ALL_LESSONS: LessonDef[] = Object.values(CURRICULUM).flat();
export const lessonById = (subject: Subject, id?: string) => CURRICULUM[subject].find((l) => l.id === id) ?? CURRICULUM[subject][0];
/** pick the day's lesson for a subject: rotates through the list by calendar day */
export const todaysLesson = (subject: Subject) => { const list = CURRICULUM[subject], d = Math.floor(Date.now() / 864e5); return list[d % list.length]; };
export function explainLesson(lesson: LessonDef, text: string, rot = 0): string | null {
  const t = text.toLowerCase();
  for (const [k, v] of Object.entries(lesson.glossary)) if (t.includes(k)) return v;
  if (/\b(again|repeat|confus|lost|don'?t (get|understand)|slow)\b/.test(t)) return `Let's go step by step. ${lesson.points[rot % lesson.points.length]}.`;
  if (/\b(example|show me|for instance)\b/.test(t)) return lesson.examples[rot % lesson.examples.length];
  if (/\b(why|how come|reason)\b/.test(t)) return lesson.whys[rot % lesson.whys.length];
  if (/\b(homework|assignment|due)\b/.test(t)) return `For homework: ${lesson.homework}`;
  if (/\b(video|clip|movie)\b/.test(t)) return "We'll watch the clip on the projector. I'll point out the key parts as it plays.";
  if (/\b(test|quiz|exam)\b/.test(t)) return "There may be a quick quiz soon. Review the points on the board and you'll be ready.";
  if (/\b(thanks|thank you)\b/.test(t)) return "You're welcome! Great job asking.";
  return null;
}
