/** One full, taught lesson per class. Each is a complete period: welcome, big idea, worked examples on the boards, questions, pictures, a clip, a hands-on lab, a recap and homework. */
import type { LessonDef } from "./curriculum";
import type { ScriptStep } from "./packs";
type S = ScriptStep;
const say = (t: string, mood?: S["mood"], gesture?: string): S => ({ say: t, mood, gesture });
const board = (side: "left" | "right", title: string, ...lines: string[]): S => ({ board: { side, title, lines } });
const ask: S = { ask: true };

export const FULL: Record<string, LessonDef[]> = {
  math: [{
    id: "fractions", subject: "math", title: "Fractions: sharing things fairly", blurb: "Parts of a whole, comparing, equivalents and adding.", pics: ["fractions", "pizza-fraction", "parabola"], videos: ["fractions"],
    intro: "Good morning, mathematicians! Today is one full lesson on fractions: what they mean, how to compare them, how to find equal ones and how to add them. By the end you will be able to share a pizza fairly with anyone.",
    points: ["A fraction names equal parts of a whole", "Denominator (bottom): how many equal parts the whole is cut into", "Numerator (top): how many of those parts you have", "A bigger denominator means smaller pieces", "Equivalent fractions name the same amount: 1/2 = 2/4 = 4/8", "Same denominator: add the numerators and keep the denominator"],
    examples: ["A pizza cut into 8 slices: you eat 3, so you ate 3/8 and 5/8 is left.", "2/4 and 1/2 cover exactly the same part of the circle, so they are equivalent.", "1/4 + 2/4 = 3/4: the pieces are the same size, so we just count them."],
    script: [
      say("Let's start with a question. If two friends share a chocolate bar, what is a fair way to split it?", "smile", "wave"), ask,
      say("Right: two EQUAL pieces. That word, equal, is the secret of fractions. If the pieces are not equal, it is not a fair fraction.", "joy"),
      board("left", "What is a fraction?", "A fraction names equal parts of a whole", "The whole is the entire thing: one pizza, one bar, one hour", "Example: 1 of 2 equal parts = 1/2"),
      say("Look at the board. The whole is the entire thing before we cut it. A fraction tells us how much of that whole we are talking about.", "smile", "point"),
      board("left", "Two numbers, two jobs", "Denominator (bottom): how many equal parts in all", "Numerator (top): how many parts we have", "3/8 means: 3 parts out of 8 equal parts"),
      say("The bottom number is the denominator. Think of the D in denominator as 'down' and 'divided into'. The top number is the numerator: it counts the parts you have.", "smile"),
      say("Imagine a pizza cut into 8 equal slices. You eat 3. Which fraction did you eat?", "smile"), ask,
      say("Three eighths, written 3 over 8. And what fraction is left? Five eighths. Notice that 3/8 plus 5/8 makes 8/8, which is one whole pizza.", "joy"),
      board("right", "Worked example 1", "Pizza cut in 8 equal slices", "Eat 3 slices: 3/8", "Left over: 8 - 3 = 5 slices = 5/8", "3/8 + 5/8 = 8/8 = 1 whole"),
      say("Here is something that surprises people. Which is bigger, 1/4 or 1/8?", "smile"), ask,
      say("One quarter is bigger! When you cut a pizza into 8 pieces instead of 4, every piece is smaller. A bigger denominator means smaller pieces.", "joy", "point"),
      board("left", "Comparing fractions", "Same numerator? The smaller denominator is the bigger piece", "1/2 > 1/3 > 1/4 > 1/8", "Same denominator? The bigger numerator is more", "5/8 > 3/8"),
      say("Now equivalent fractions. Imagine one half of a pizza. If I cut every slice in half again, I now have 2 out of 4 slices. Is that still the same amount of pizza?", "smile"), ask,
      say("Yes. The amount of pizza did not change, only how we cut it. So 1/2 equals 2/4, and 2/4 equals 4/8. We multiplied the top and the bottom by the same number.", "joy"),
      board("right", "Making equivalent fractions", "Multiply the top AND bottom by the same number", "1/2 x 2/2 = 2/4", "1/2 x 4/4 = 4/8", "The amount stays the same; only the cutting changes"),
      say("Be careful. If you change only the top or only the bottom, the amount changes. Both numbers must change by the same factor.", "neutral"),
      say("Last skill: adding. When the denominators match, the pieces are the same size, so we simply count pieces. One quarter plus two quarters is three quarters.", "smile"),
      board("left", "Adding fractions", "Same denominator: add the numerators", "Keep the denominator the same", "1/4 + 2/4 = 3/4", "Different denominators? Make them equivalent first"),
      say("Why do we keep the denominator? Because we are not changing the size of the pieces. We are only counting how many we have, just like 2 apples plus 3 apples is 5 apples.", "joy"),
      say("Try one yourself. A pizza is cut in 6 slices. You eat 1 slice and your friend eats 2. How much did you eat together?", "smile"), ask,
      say("Three sixths. And look: 3/6 is the same as 1/2, so together you ate half the pizza. Equivalent fractions and adding working together!", "joy", "clap"),
      say("Now let's see it on the screen. Watch how the shapes are divided, and notice the numerator and denominator in each picture.", "smile"),
    ],
    lab: { id: "pizza", title: "Pizza Party", intro: "Serve each classmate exactly the fraction they ask for. Click the slices to hand them out." },
    wrap: "Great work today. Remember: equal parts make a fraction, the bottom says how many parts, the top says how many you have, and same-size pieces can be added by counting.",
    homework: "Draw three identical rectangles. Shade 1/2 of the first, 2/4 of the second and 4/8 of the third. Write one sentence about what you notice. Then add 1/8 + 3/8 and show it with a drawing.",
    glossary: { fraction: "A fraction is a number that names equal parts of a whole.", whole: "The whole is the entire thing before it is divided.", numerator: "The numerator is the top number: how many parts you have.", denominator: "The denominator is the bottom number: how many equal parts make the whole.", equivalent: "Equivalent fractions look different but name the same amount, like 1/2 and 2/4.", compare: "To compare fractions, look at the size of the pieces and how many you have.", add: "To add fractions with the same denominator, add the numerators and keep the denominator.", equal: "Equal means exactly the same size." },
    whys: ["The parts must be equal, otherwise 1/4 would not always mean the same amount.", "More pieces means smaller pieces, which is why 1/8 is smaller than 1/4.", "Equivalent fractions work because cutting every piece in half doubles both numbers and the amount stays the same.", "We keep the denominator when adding because the size of the pieces does not change."],
  }],
  ela: [{
    id: "theme", subject: "ela", title: "Finding the theme of a story", blurb: "Plot, change, evidence and writing a theme sentence.", pics: ["organizer", "simile"], videos: ["theme"],
    intro: "Welcome, readers and writers. Today's full lesson is about theme: the big message hiding inside a story. We will read a short fable together, hunt for evidence, and write a theme in a full sentence.",
    points: ["Plot: what happens in the story", "Character change: how a character is different at the end", "Evidence: details and quotes from the text that prove your idea", "A theme is a message, written as a full sentence", "A topic is one word; a theme says something about it", "Good readers use clues to make inferences"],
    examples: ["Topic: perseverance. Theme: 'If you keep trying, you can reach your goal.'", "The hare naps because he is sure he will win. The tortoise keeps walking. The ending shows what the author wants us to learn.", "Not a theme: 'friendship' (one word). A theme says something about it: 'True friends help each other when it is hard.'"],
    script: [
      say("Hands up if you have ever finished a story and thought, 'Oh, so THAT was the point.' That feeling is finding the theme.", "smile", "wave"), ask,
      board("left", "Theme vs topic", "Topic: the subject in one or two words (friendship)", "Theme: the message about the topic, in a full sentence", "'True friends help each other.'"),
      say("A topic tells us what a story is about. A theme tells us what the story is TRYING TO SAY about it. Topic: courage. Theme: 'Being brave means doing the right thing even when you are afraid.'", "smile", "point"),
      say("Let's practice with a story you may know: The Tortoise and the Hare. Listen for what happens, then for what changes.", "smile"),
      board("right", "The plot, in order", "1. The hare brags that he is the fastest runner", "2. The tortoise challenges him to a race", "3. The hare sprints ahead, then naps", "4. The tortoise keeps walking, slow and steady", "5. The tortoise crosses the finish line first"),
      say("That is the plot: the events in order. Step one is simply to ask, what happens?", "smile"),
      say("Step two. What CHANGES? At the start the hare feels sure he will win. At the end, what has he learned? What about the tortoise?", "smile"), ask,
      say("The hare learns that being fast is not enough when you stop trying. The tortoise shows that steady effort pays off. Stories are about change, and the change points to the lesson.", "joy"),
      board("left", "Step 3: Evidence", "Evidence = a detail from the text that supports your idea", "The hare 'lay down and took a nap'", "The tortoise 'never stopped, not even once'", "Evidence makes a theme something we can show"),
      say("Step three is evidence. We never just guess a theme. We point to the text. Which detail shows the hare was overconfident?", "smile"), ask,
      say("Exactly: he took a nap because he was sure he could not lose. That is our evidence, and evidence turns a guess into an argument.", "joy"),
      board("right", "Step 4: Write the theme sentence", "Topic: perseverance", "Say something about it, as a full sentence", "'Slow and steady effort beats quick but careless work.'", "Check: does the plot prove it?"),
      say("Step four: write the theme as a complete sentence and check it against the plot. Would the story still make sense with that message? Yes, so it works.", "smile"),
      say("One more skill is making inferences. The story never says the hare was embarrassed, but we infer it from clues. An inference is an idea you work out from clues plus what you already know.", "smile"),
      say("Now try one on your own. A girl practices piano every day. At her first recital she freezes, but she tries again the next month and plays well. Which of these is a theme: 'piano' or 'Practice and trying again help you improve'?", "smile"), ask,
      say("The second one! 'Piano' is only a topic. The sentence says something about practice, so it is a theme.", "joy", "clap"),
      board("left", "Theme checklist", "What happens? (plot)", "What changes? (character)", "What proves it? (evidence)", "Write the message as a sentence (theme)"),
      say("This checklist works for any story, from a picture book to a novel. Look at the pictures on the screen, then we will watch a short clip and look for the theme together.", "smile"),
    ],
    lab: { id: "cardsort", cfg: "tortoise", title: "Story Builder", intro: "Put the events of the story in order, then pick the theme the events prove." },
    wrap: "Remember the four steps: what happens, what changes, what is the evidence, then state the theme in a full sentence.",
    homework: "Pick a story, movie or book you know. Write its theme as one full sentence, add one piece of evidence, and tell why that evidence proves your theme.",
    glossary: { theme: "The theme is the big message or lesson of a story, written as a full sentence.", topic: "A topic is what a story is about, in one or two words.", evidence: "Evidence is a detail or quote from the text that supports your idea.", plot: "The plot is the series of events in a story.", character: "A character is a person or creature in a story.", conflict: "Conflict is the problem or struggle that drives the story.", inference: "An inference is an idea you figure out from clues in the text.", moral: "A moral is a lesson that a fable or story teaches." },
    whys: ["We use evidence so the theme is something we can show, not just a guess.", "Looking at what changes works because stories are about change, and the change points to the lesson.", "A theme is a full sentence because it makes a statement about life, not just a subject.", "Checking the plot against your theme tells you whether the theme really fits."],
  }],
  science: [{
    id: "photosynthesis", subject: "science", title: "Photosynthesis: how plants make food", blurb: "Plant cells, light, water, air and the sugar they build.", pics: ["plant-cell", "photosynthesis", "water-cycle"], videos: ["photosynthesis"],
    intro: "Welcome, scientists! Today's question is a strange one: how does a plant eat? Plants have no mouths and cannot hunt, yet they grow enormous. By the end of this full lesson you will be able to explain exactly how.",
    points: ["Plants make their own food using light: photosynthesis", "Inputs: sunlight, water (through roots), carbon dioxide (through leaves)", "Outputs: glucose (sugar for food) and oxygen", "Chlorophyll in the chloroplasts captures the light", "The word equation: carbon dioxide + water + light energy -> glucose + oxygen", "Photosynthesis happens mostly in leaves, and feeds almost every food chain"],
    examples: ["A plant on a sunny windowsill bends toward the light.", "Water goes up through the roots, carbon dioxide enters through tiny holes in the leaves called stomata.", "The oxygen we breathe is made by plants and algae."],
    script: [
      say("Let's start with a mystery. A tiny seed becomes a huge tree. Where does all that wood and leaf come from? Take a guess.", "smile", "wave"), ask,
      say("Many people guess soil. Here is the surprise: most of a plant's mass comes from the AIR and from water. That is the magic of photosynthesis.", "joy"),
      board("left", "Photosynthesis", "Photo = light, synthesis = putting together", "Plants use light energy to build their own food", "Producers make food; consumers eat it"),
      say("The word photosynthesis means 'putting together with light'. Plants are producers: they make food. Animals are consumers: we eat plants, or we eat animals that ate plants.", "smile", "point"),
      say("Where does it happen? Inside the plant cell. Look at the plant cell on the wall.", "smile"),
      board("right", "Inside a plant cell", "Cell wall: strong outer support", "Chloroplasts: tiny green factories for photosynthesis", "Vacuole: stores water", "Nucleus: the control center with DNA", "Mitochondria: release energy from food"),
      say("The star is the chloroplast. Each one is filled with chlorophyll, the green pigment that captures sunlight. That is why leaves are green.", "smile", "point"),
      say("Now the ingredients. Can you name what a plant needs? Think about what it gets from the sun, from the ground, and from the air.", "smile"), ask,
      board("left", "The recipe", "Light energy: from the Sun", "Water: taken in by roots", "Carbon dioxide: enters through leaf pores (stomata)", "Chlorophyll: captures the light"),
      say("Light from the Sun, water from the roots and carbon dioxide from the air. Plants breathe in carbon dioxide, the gas that we breathe out.", "smile"),
      board("right", "The results", "Glucose: a sugar the plant uses for energy and growth", "Oxygen: released into the air", "Word equation:", "carbon dioxide + water + light -> glucose + oxygen"),
      say("The products are glucose, a sugar the plant uses for food and for building stems and leaves, and oxygen, which the plant releases. Oxygen is basically a leftover that we need to survive.", "joy"),
      say("Let's check your thinking. If I put a plant in a closet with no light for two weeks, what do you predict happens?", "smile"), ask,
      say("It becomes pale and weak, because without light the recipe cannot run and the plant cannot make glucose. Scientists do this exact test, which is called an experiment.", "joy"),
      board("left", "Fair test: plant in the dark", "Question: does a plant need light?", "Change one thing: light or no light", "Keep everything else the same: water, soil, type of plant", "Observe and record for 2 weeks"),
      say("Notice we change only ONE thing and keep everything else the same. That is what makes it a fair test.", "smile"),
      say("Why does this matter beyond one plant? Almost every food chain begins with photosynthesis, and plants and algae make much of the oxygen in our air.", "smile"),
      say("Look at the pictures on the screen. Follow the arrows: what goes in, and what comes out? Then we will watch a clip and you will run the lab.", "smile"),
    ],
    lab: { id: "photosynth", title: "Grow the Plant", intro: "Give your plant sunlight, water and carbon dioxide in the right balance and grow it tall." },
    wrap: "Sunlight, water and carbon dioxide go in. Glucose and oxygen come out. The chloroplasts, full of chlorophyll, are the factories.",
    homework: "Observe a plant at home or outside for a week. Draw it on day one and day seven and write two sentences about how it changed and what it needs.",
    glossary: { photosynthesis: "Photosynthesis is how plants turn sunlight, water and carbon dioxide into sugar and oxygen.", chlorophyll: "Chlorophyll is the green pigment that captures sunlight.", chloroplast: "A chloroplast is the part of a plant cell where photosynthesis happens.", glucose: "Glucose is the sugar plants make for energy.", oxygen: "Oxygen is the gas plants release that we breathe.", "carbon dioxide": "Carbon dioxide is the gas plants take in from the air.", producer: "A producer makes its own food, like a plant.", stomata: "Stomata are tiny holes in leaves that let gases in and out.", vacuole: "A vacuole is the part of a plant cell that stores water." },
    whys: ["Plants cannot hunt or eat, so they make food from light.", "Light is the energy that powers the reaction.", "Oxygen is a leftover the plant releases.", "Leaves are green because chlorophyll reflects green light and absorbs the rest."],
  }],
  history: [{
    id: "silkroad", subject: "history", title: "The Silk Road: trade that changed the world", blurb: "Routes, goods, cities and the ideas that traveled.", pics: ["silk-map", "timeline"], videos: ["silkroad"],
    intro: "Welcome, historians! Today we travel the greatest trading highway in the ancient world: the Silk Road. We will follow the routes, see what moved along them, and discover why a road for selling cloth changed religion, technology and food on three continents.",
    points: ["A network of trade routes, not one road, linking China, Central Asia, the Middle East and Europe", "It was used for about 1,500 years, starting around 130 BCE", "Silk, spices, paper, porcelain and horses traveled; so did ideas, religions and inventions", "Few traders traveled the whole way: goods were passed from trader to trader", "Caravans of camels crossed deserts and mountains, stopping at oasis towns", "Cities along the way grew rich, and cultures mixed"],
    examples: ["Silk was made only in China at first, and the method was kept secret for centuries.", "Papermaking spread west along the routes, and so did new ideas and stories.", "Oasis towns like Samarkand grew rich from trade."],
    script: [
      say("Imagine you want to sell a beautiful silk robe to someone 4,000 miles away, with no airplanes, no trucks and no internet. How would you do it?", "smile", "wave"), ask,
      say("That was the challenge, and the answer was the Silk Road. First, a common mistake: it was not one road. It was a web of many routes.", "joy"),
      board("left", "What was the Silk Road?", "A network of trade routes, not a single road", "Linked China, Central Asia, the Middle East and Europe", "Used for roughly 1,500 years, starting about 130 BCE", "Named for the silk traded from China"),
      say("Look at the map on the wall. The routes crossed deserts, mountains and seas. Some people say there were also sea routes that joined the story.", "smile", "point"),
      say("Now, who traveled it? Almost nobody went the whole way. A merchant would carry goods part of the way and sell to the next trader. So goods moved like a relay race.", "smile"),
      board("right", "A relay of traders", "Goods passed from trader to trader", "Each stop added a profit", "Far-away goods became very expensive", "Silk, paper, spices and porcelain went west", "Horses, glass, gold and wool went east"),
      say("That is why silk cost so much in Rome: every trader along the way took a share. Which goods can you spot on the board that went west and which went east?", "smile"), ask,
      say("Right. Traders moved silk, spices, paper and porcelain westward and horses, glass and metals eastward. Trade is exchanging goods or services, and everybody hoped to gain.", "joy"),
      board("left", "Traveling by caravan", "Caravan: a group of traders traveling together", "Camels: can go days without water and carry heavy loads", "Oasis: a place in the desert with water", "Caravanserai: roadside inns for rest and trading"),
      say("Why camels? They can carry heavy loads and go a long time without water. And why caravans? Safety in numbers, because the journey was dangerous.", "smile", "point"),
      say("A question for you. If you were a trader at an oasis town, why would a lot of people want to settle there?", "smile"), ask,
      say("Because traders must stop for water and rest, and they need to buy food and supplies. Oasis towns such as Samarkand grew rich by hosting travelers and trading.", "joy"),
      board("right", "More than goods", "Papermaking moved west from China", "Religions such as Buddhism spread along the routes", "Foods, stories and music traveled too", "Sadly, diseases also moved along the routes"),
      say("Here is the big idea. When people meet to trade, they share ideas too. Paper-making, religions, music and new foods all traveled, and so did diseases, which is a part of the story historians study.", "smile"),
      say("Look at the timeline on the screen to see when the routes were busiest. Notice that the road lasted much longer than most empires.", "smile"),
      say("Why did it fade? Over time, sea routes became cheaper and faster, and powerful empires changed. But its legacy, connected cultures, still shapes our world today.", "smile"),
      board("left", "Why it matters", "Connected distant cultures", "Spread inventions, religions and foods", "Created rich trading cities", "Still a symbol of exchange between peoples"),
      say("Last question. Which do you think mattered more to the world, the silk itself or the ideas that traveled with it?", "smile"), ask,
      say("Historians still debate this! Good historians give reasons for their opinions. Watch the clip next and listen for evidence.", "joy"),
    ],
    lab: { id: "cardsort", cfg: "silkroad", title: "Trade Match", intro: "Send each good to the city where it was famous." },
    wrap: "The Silk Road was a web of routes where goods and ideas moved by relay. Remember caravans, oasis towns, and the way trade shares ideas.",
    homework: "List three things traded on the Silk Road, say where each came from, and write two sentences on one idea that traveled along with goods.",
    glossary: { caravan: "A caravan is a group of traders traveling together, often with camels.", oasis: "An oasis is a place in the desert with water.", trade: "Trade is exchanging goods or services.", silk: "Silk is a smooth fabric made from silkworm threads.", route: "A route is a path from one place to another.", merchant: "A merchant is a person who buys and sells goods.", legacy: "A legacy is something that lasts and still affects us after the time is over.", empire: "An empire is a large area ruled by one government." },
    whys: ["Silk was rare and valuable, so people traveled far to trade for it.", "Camels can go long distances without water.", "When people meet to trade, they also share ideas.", "Goods passed from trader to trader, so each stop raised the price."],
  }],
  careers: [{
    id: "find", subject: "careers", title: "Finding your path", blurb: "Interests, skills, values, clusters and a first plan.", pics: ["career-path", "career-clusters", "pay-paths"], videos: [],
    intro: "Welcome to CarryingCareers! Today is one full lesson on finding the career path that fits YOU. Every career of every type starts with knowing yourself, then exploring, then planning.",
    points: ["Interests: what you enjoy doing", "Skills: what you can do well, and what you can learn", "Values: what matters to you, like helping, creating, security or adventure", "The best fit sits where all three overlap", "Careers are grouped into 16 clusters, so you can explore by interest", "A career path: explore, research, train, build a resume, apply, keep growing"],
    examples: ["Enjoys fixing bikes (interest), patient with details (skill), likes seeing things work (value): mechanic, engineer or technician.", "Loves explaining things, speaks clearly, wants to help others grow: teacher or trainer.", "Likes animals, calm under pressure, wants to care for living things: veterinary technician."],
    script: [
      say("Raise your hand if someone has ever asked, 'What do you want to be when you grow up?' It can be a tough question, so today we give you a method for answering it.", "smile", "wave"), ask,
      say("Nobody needs a final answer today. Your path changes as you learn. What you DO need is a way to explore, and it starts with three questions.", "joy"),
      board("left", "Three questions about you", "Interests: what do I enjoy?", "Skills: what am I good at, or want to learn?", "Values: what matters to me?", "The best fit is where all three overlap"),
      say("Interests are what you enjoy. Skills are what you can do well, and skills can be learned and practiced. Values are what matter to you: helping people, being creative, earning well, having time for family, or feeling secure.", "smile", "point"),
      say("Let's try an example. Sam enjoys fixing bikes, is patient with small details, and likes seeing something work again. What jobs might fit Sam?", "smile"), ask,
      board("right", "Example: Sam", "Interest: fixing bikes", "Skill: patience with details", "Value: seeing things work", "Fits: mechanic, engineer, technician, repair specialist"),
      say("Great ideas! Notice that Sam did not pick one job. Sam found a whole GROUP of jobs. That group is called a career cluster.", "joy"),
      board("left", "Career clusters", "16 groups of related careers", "Examples: Health Science, Information Technology", "Architecture and Construction, Agriculture", "Arts and Media, Education, Business, Law and Public Safety", "Each cluster holds many different jobs"),
      say("Look at the clusters on the wall. Which cluster sounds most interesting to you right now? There is no wrong answer.", "smile"), ask,
      say("Thank you for sharing. Your answer may change, and that is fine. The idea is to explore on purpose.", "joy"),
      say("Next, how do you find out what a job is really like? You can read about it, watch a video, talk with someone who does it, and try a small project.", "smile"),
      board("right", "How to explore a career", "Read: what do people in this job do all day?", "Ask: talk to someone who does it", "Try: a club, a volunteer day, a small project", "Compare: pay, training time and outlook"),
      say("Different routes take different amounts of training. Some careers need a few months for a certificate, some need a degree, some need an apprenticeship where you learn while you work.", "smile", "point"),
      board("left", "Paths to a career", "Certificate or short course", "Apprenticeship: paid, learning on the job", "College or university degree", "Military or national service", "Starting work and growing your skills"),
      say("Which path is best? The one that fits your goal, your time and your budget. Many people change paths more than once, and that is normal.", "smile"),
      board("right", "Your path in steps", "1. Explore your interests, skills and values", "2. Research two or three jobs", "3. Choose training that fits", "4. Build a resume and practice interviews", "5. Apply, learn, keep growing"),
      say("Here is something you can do at any age. Write down one interest, one skill and one value. That is the start of your own plan.", "joy"),
      say("Look at the picture on the screen with the steps. Then take the sort lab, where you place each statement as an interest, a skill or a value.", "smile"),
    ],
    lab: { id: "cardsort", cfg: "careers-find", title: "Interests, Skills, Values", intro: "Sort each statement into Interests, Skills or Values." },
    wrap: "Interests, skills and values all point somewhere. Explore on purpose, try small things, and keep your plan flexible.",
    homework: "Write one interest, one skill and one value you have. Then pick one career cluster and find two jobs inside it. Write one question you would ask someone with that job.",
    glossary: { interest: "An interest is something you enjoy doing or learning about.", skill: "A skill is something you can do well. Skills can be learned and practiced.", value: "A value is something that matters to you, like helping others, creativity or security.", career: "A career is the work you do over many years, often growing from job to job.", strength: "A strength is something you are naturally good at.", cluster: "A career cluster is a group of related jobs.", apprenticeship: "An apprenticeship is paid training where you learn a trade on the job.", certificate: "A certificate is a short training program that proves a skill.", resume: "A resume is a page that lists your skills, work and learning." },
    whys: ["Careers fit better when they match what you enjoy, what you are good at, and what you care about.", "Skills can be learned, so you do not need to be great at everything today.", "Values matter because a job that fits them feels meaningful, not only paid.", "Trying small things before big choices saves time and money."],
  }],
  life: [{
    id: "money", subject: "life", title: "Money basics: earn, spend, save", blurb: "Income, needs and wants, a budget and a savings habit.", pics: ["budget-split", "life-wheel", "first-aid"], videos: [],
    intro: "Welcome to Life Lessons! Today is one full lesson on the money basics every independent person uses: where money comes from, where it goes, and how to keep some for the future.",
    points: ["Income is money you receive; expenses are money you spend", "Needs come first (food, home, health, safety); wants come next", "A budget is a plan: about 50% needs, 30% wants, 20% savings", "Pay yourself first: set aside savings before you spend", "Small amounts saved often grow into big ones", "Wait a day before a big purchase to avoid impulse buys"],
    examples: ["Needs: groceries, rent, medicine. Wants: games, snacks, new shoes.", "Save 10 out of every 100 you receive and after ten rounds you have 100 saved.", "Before a big purchase, wait one day. If you still want it, then decide."],
    script: [
      say("Quick question: where does money come from? Think of someone you know and how they get it.", "smile", "wave"), ask,
      say("Great answers: pay from a job, a gift, an allowance, or selling something. All of these are called income, which is money coming IN.", "joy"),
      board("left", "Money in, money out", "Income: money you receive (pay, allowance, gifts)", "Expense: money you spend", "If expenses are bigger than income, you run short", "If income is bigger, you can save"),
      say("The simplest money rule in the world is this: do not spend more than you receive. Everything else builds from there.", "smile", "point"),
      say("Now, spending. Not everything is equally important. Is food a need or a want? What about a new video game?", "smile"), ask,
      board("right", "Needs and wants", "Needs: food, a safe home, health care, basic clothes, transport to school or work", "Wants: games, snacks, brand-name shoes, extra apps", "Needs come first. Wants come after, if there is room."),
      say("Food is a need, a game is a want. Sometimes it is a mix, like shoes: you need shoes, but you may want an expensive pair. Notice how that changes the choice.", "smile"),
      say("To handle this, people use a budget. A budget is just a plan for your money before you spend it.", "smile"),
      board("left", "The 50/30/20 plan", "50% needs", "30% wants", "20% savings and paying off debt", "Adjust the numbers to fit your life"),
      say("This is a starting point, not a law. If you earn 100 dollars, that is about 50 for needs, 30 for wants, and 20 for savings. Let's look at the chart on the wall.", "smile", "point"),
      say("Try it. If you receive 40 dollars, how much would be set aside for savings with the 20 percent rule?", "smile"), ask,
      say("Eight dollars. Twenty percent of forty is eight. And needs would be twenty and wants twelve. Does the total add to forty?", "joy"),
      board("right", "Worked example", "Income: $40", "Needs 50%: $20", "Wants 30%: $12", "Savings 20%: $8", "$20 + $12 + $8 = $40"),
      say("A big secret of saving is to pay yourself first. Put your savings aside the moment money arrives, instead of saving what is left over. If you wait for leftovers, usually there are none.", "smile"),
      say("Why does small saving matter? Save 10 out of every 100 you receive. After ten rounds that is 100 saved, without ever feeling a big sacrifice.", "smile"),
      board("left", "Beating impulse buys", "Pause: wait one day before a big purchase", "Ask: do I need it, or just want it right now?", "Compare: is there a cheaper or used option?", "Decide: still want it? Then buy with a plan"),
      say("Companies are very good at making things look urgent. A one-day pause is a free, powerful tool. Have you ever wanted something badly and then forgotten it a week later?", "smile"), ask,
      say("Most of us have. That is exactly why waiting helps. Last, set a goal: saving for something specific is easier than saving 'someday'.", "joy"),
      say("Look at the pictures, then try the sorting lab: place each item under Needs, Wants or Savings.", "smile"),
    ],
    lab: { id: "cardsort", cfg: "life-money", title: "Needs, wants, savings", intro: "Sort each item into Needs, Wants or Savings." },
    wrap: "Needs first, then wants, and always a little for the future. A simple plan beats good intentions.",
    homework: "List three needs, three wants and one thing you could save for. Then split a pretend $50 using the 50/30/20 plan and show your math.",
    glossary: { income: "Income is money you receive, like pay or allowance.", expense: "An expense is money you spend.", need: "A need is something you must have to live and stay healthy.", want: "A want is something nice to have but not necessary.", savings: "Savings is money you set aside for later.", budget: "A budget is a plan for how you will use your money.", "impulse buy": "An impulse buy is something bought quickly without planning.", goal: "A goal is something you want to achieve." },
    whys: ["Needs come first because they keep you healthy and housed.", "Paying yourself first makes saving automatic instead of leftover.", "Waiting a day stops impulse buys.", "A budget helps because you decide before the money is tempted."],
  }],
};
