/** Teacher personalities: how each one moves, gestures, sounds and reacts (smiles, frowns, upset, frustration, joy). */
export type Emotion = "neutral" | "smile" | "joy" | "frown" | "upset" | "frustrated" | "surprised" | "thinking" | "stern";
export type Reaction = "welcome" | "correct" | "wrong" | "wrongAgain" | "noHands" | "thanks" | "think" | "wrap" | "ask";
export interface React { e: Emotion; g?: string; ms: number; lines: string[] }
export interface Persona { base: Emotion; walk: number; gestures: string[]; fidget: [number, number]; voice: { pitch: number; rate: number }; r: Record<Reaction, React> }
const R = (e: Emotion, g: string | undefined, lines: string[], ms = 2800): React => ({ e, g, ms, lines });
const mk = (p: Omit<Persona, "r"> & { r: Partial<Record<Reaction, React>> }): Persona => ({ ...p, r: { welcome: R("smile", "wave", ["Welcome!"], 2400), correct: R("joy", "clap", ["Yes!"]), wrong: R("thinking", "chin", ["Hmm, not quite."]), wrongAgain: R("frustrated", "headhands", ["Okay, let's slow down."], 3400), noHands: R("stern", "crossed", ["I see a lot of quiet faces."]), thanks: R("smile", "shrug", [""]), think: R("thinking", "chin", [""], 2400), wrap: R("joy", "clap", ["Nice work today."], 3000), ask: R("smile", "explain", [""], 2200), ...p.r } });
export const PERSONAS: Record<string, Persona> = {
  nerdy: mk({ base: "smile", walk: 1.12, gestures: ["explain", "finger", "chin"], fidget: [2.4, 4.2], voice: { pitch: 1.08, rate: 1.04 }, r: {
    welcome: R("smile", "wave", ["Welcome back, mathematicians!"], 2600), correct: R("joy", "clap", ["Excellent!", "Precisely!"]), wrong: R("thinking", "chin", ["Hmm, let's recheck that."]),
    wrongAgain: R("frustrated", "headhands", ["Okay, okay. Let's slow down and do it together."], 3600), noHands: R("stern", "crossed", ["I see a lot of quiet faces."]) } }),
  dreamy: mk({ base: "smile", walk: 0.82, gestures: ["wave", "explain", "chin"], fidget: [3.2, 5.2], voice: { pitch: 0.96, rate: 0.88 }, r: {
    welcome: R("smile", "wave", ["Hello, my friends."], 2600), correct: R("joy", "wave", ["What a beautiful answer."]), wrong: R("frown", "shrug", ["Ah, that is a lovely try."]),
    wrongAgain: R("upset", "facepalm", ["Oh... let's breathe and look at it again."], 3600), noHands: R("surprised", "shrug", ["No hands? The words are waiting for you."]) } }),
  curious: mk({ base: "smile", walk: 1.22, gestures: ["finger", "explain", "shrug", "wave"], fidget: [1.8, 3.4], voice: { pitch: 1.1, rate: 1.12 }, r: {
    welcome: R("surprised", "wave", ["Oh good, you're here! Today is going to be fun."], 2600), correct: R("joy", "cheer", ["Whoa, yes!", "That's it exactly!"]), wrong: R("thinking", "chin", ["Interesting! Let's test that."]),
    wrongAgain: R("frustrated", "headhands", ["Argh, science is tricky, but we will get it!"], 3600), noHands: R("surprised", "shrug", ["Nobody? Come on, take a guess!"]) } }),
  funny: mk({ base: "smile", walk: 1.06, gestures: ["shrug", "explain", "wave", "finger"], fidget: [1.8, 3.4], voice: { pitch: 0.92, rate: 1.0 }, r: {
    welcome: R("joy", "wave", ["Ladies and gentlemen, history class!"], 2600), correct: R("joy", "cheer", ["Boom! Nailed it!", "Look at you!"]), wrong: R("smile", "shrug", ["Ooh, so close!"]),
    wrongAgain: R("frustrated", "headhands", ["Come on, history is on your side!"], 3600), noHands: R("stern", "crossed", ["Hello? Is this thing on?"]) } }),
  kind: mk({ base: "smile", walk: 0.96, gestures: ["explain", "wave"], fidget: [3, 5], voice: { pitch: 0.86, rate: 0.95 }, r: {
    correct: R("joy", "clap", ["That's wonderful."]), wrong: R("frown", "shrug", ["That's okay, try again."]), wrongAgain: R("upset", "facepalm", ["It's alright. We'll get there together."], 3600) } }),
  cheerful: mk({ base: "joy", walk: 1.1, gestures: ["wave", "explain", "shrug"], fidget: [2, 3.6], voice: { pitch: 1.16, rate: 1.08 }, r: {
    welcome: R("joy", "wave", ["Good morning, sunshines!"], 2600), correct: R("joy", "cheer", ["Fantastic!"]), wrong: R("smile", "shrug", ["Almost!"]), wrongAgain: R("frustrated", "headhands", ["Oh my goodness, let's try again."], 3600) } }),
};
const F = (id: string, base: Emotion, walk: number, gestures: string[], fidget: [number, number], voice: { pitch: number; rate: number }, greet: string, praise: string, r: Partial<Record<Reaction, React>>) => { PERSONAS[id] = mk({ base, walk, gestures, fidget, voice, r: { welcome: R("smile", "wave", [greet], 3000), correct: R("joy", "clap", [praise], 3000), ...r } }); };
F("tanaka", "smile", 0.9, ["finger", "explain", "chin"], [3, 5], { pitch: .85, rate: .82 }, "Good morning. Please be seated, and be rational.", "Excellent. That answer is integral to the class.", { wrong: R("thinking", "chin", ["Hmm. Not quite. Let us check our steps."]), wrongAgain: R("frown", "finger", ["Step one: breathe. Let's go again."], 3400), noHands: R("stern", "crossed", ["I see a calculator under the desk. Its days are numbered."]), wrap: R("smile", "explain", ["Well done today."], 2800) });
F("ayrissa", "smile", 1.15, ["wave", "explain", "shrug", "cheer"], [1.8, 3.2], { pitch: 1.18, rate: 1.14 }, "Good morning, my brilliant people! Pens out, energy up, let's WRITE!", "YES! Say that again, louder, for the people in the back!", { correct: R("joy", "cheer", ["YES! Say that again, louder!", "That's it! That's the one!"], 3000), wrong: R("smile", "shrug", ["Ooh, almost, my brilliant one!"]), wrongAgain: R("surprised", "shrug", ["Okay okay, let's try that another way!"], 3400), noHands: R("surprised", "wave", ["Come on, my brilliant people, hands up!"]), wrap: R("joy", "cheer", ["Journal tonight. Your voice matters!"], 3000) });
F("okafor", "smile", 0.95, ["chin", "finger", "crossed"], [3, 5.5], { pitch: .95, rate: .92 }, "Goggles on, bags under the bench. Good morning.", "Correct, to three significant figures. I'm impressed.", { wrong: R("thinking", "chin", ["Incorrect. Recalculate."]), wrongAgain: R("frustrated", "headhands", ["That is not a beaker of juice. Again."], 3400), noHands: R("stern", "crossed", ["I can wait. I have all period."]), wrap: R("smile", "finger", ["Wash your hands. Twice."], 2800) });
F("obrien", "joy", 1.0, ["shrug", "explain", "wave", "finger"], [1.8, 3.4], { pitch: .75, rate: .95 }, "Gather round, gather round! Today... we march on Rome.", "Ha! A scholar among us! Rome would have made you a senator.", { correct: R("joy", "cheer", ["Ha! A scholar among us!"], 3000), wrong: R("smile", "shrug", ["Ah, close, but the plot thickens!"]), wrongAgain: R("frustrated", "headhands", ["By the beard of Caesar!"], 3400), noHands: R("surprised", "shrug", ["Silence? Even the Roman Senate had more to say!"]), wrap: R("joy", "wave", ["History waits for no one. Off with ye!"], 3000) });
F("haddad", "smile", 0.9, ["chin", "explain", "finger"], [3.2, 5.5], { pitch: .7, rate: .85 }, "Welcome, travelers. Where in the world shall we begin today?", "Good. You didn't just answer. You thought. That is the difference.", { correct: R("joy", "clap", ["Good. You didn't just answer. You thought."], 3000), wrong: R("thinking", "chin", ["Hmm. Take three seconds. Think again."]), wrongAgain: R("frown", "shrug", ["It's alright. Let's read the map another way."], 3400), noHands: R("thinking", "chin", ["I'll wait. Silence is how we think."]), wrap: R("smile", "explain", ["Look at the sky on your walk home."], 2800) });
F("park", "joy", 1.25, ["wave", "cheer", "shrug", "finger"], [1.6, 3], { pitch: 1.35, rate: 1.18 }, "Hi hi hi! Okay, log in, it's gonna be SO fun.", "It compiled?! First try?! Double thumbs up, you legend.", { correct: R("joy", "cheer", ["It compiled?! Double thumbs up!"], 3000), wrong: R("thinking", "shrug", ["Mm, compile error! Let's debug it."]), wrongAgain: R("frustrated", "headhands", ["Argh, null pointer in my brain! Restart!"], 3400), noHands: R("surprised", "shrug", ["Anyone? Hello? Is this thing on?"]), wrap: R("joy", "wave", ["Commit your work! Bye!"], 2800) });
F("larsen", "smile", 0.85, ["finger", "explain", "chin"], [3, 5], { pitch: 1.05, rate: .85 }, "Good morning, my future grown-ups. Let us see what life has to teach today.", "Very good. You think like a grown-up now. Dangerous.", { wrong: R("thinking", "finger", ["Ah, but... look again."]), wrongAgain: R("frown", "facepalm", ["Oh dear. Even grown-ups get this one wrong at first."], 3400), noHands: R("stern", "crossed", ["Ah. A room full of quiet thinkers."]), wrap: R("smile", "explain", ["Try one thing for yourself this week."], 2800) });
F("raman", "smile", 0.85, ["explain", "chin", "wave"], [3, 5], { pitch: 1.1, rate: .88 }, "Good morning, my dears. Open your books to where the story left us.", "Oh, that's lovely. Write that down before it flies away.", { wrong: R("smile", "shrug", ["A lovely try, dear."]), wrongAgain: R("upset", "facepalm", ["Oh, my dear. Let us read it once more."], 3400), noHands: R("thinking", "chin", ["Silence, like a held breath. Who will speak?"]), wrap: R("smile", "explain", ["Read chapter nine tonight."], 2800) });
export const personaOf = (key?: string): Persona => PERSONAS[key ?? ""] ?? PERSONAS.kind;
