/** Practice mini-games, one per class. Short, friendly, no timers and no losing: the class teacher cheers you on (and gently coaches when you miss).
 *  Finishing a game counts toward the daily quest. They are built from the same ideas as the lessons so they double as review. */
import { Quests } from "./quests";
import { TEACHER_BY_SUBJECT } from "../hall3d/roster";
type Subj = "math" | "ela" | "science" | "history" | "careers" | "life";
const E = <K extends keyof HTMLElementTagNameMap>(tag: K, cls = "", parent?: HTMLElement, text = "") => { const e = document.createElement(tag); if (cls) e.className = cls; if (text) e.textContent = text; parent?.appendChild(e); return e; };
const rnd = <T,>(a: T[]) => a[Math.floor(Math.random() * a.length)];
const shuffle = <T,>(a: T[]) => { const b = a.slice(); for (let i = b.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [b[i], b[j]] = [b[j], b[i]]; } return b; };
const CSS = `.mg{position:fixed;inset:0;z-index:75;background:rgba(74,59,63,.5);display:none;align-items:center;justify-content:center;font-family:"Fredoka","Trebuchet MS",system-ui,sans-serif;color:#4A3B3F}.mg.show{display:flex}
.mg-p{background:#F3E7CF;border:1px solid #fff;border-radius:20px;box-shadow:0 3px 0 #C9B28A,0 18px 36px rgba(0,0,0,.4);width:min(640px,96vw);max-height:94vh;overflow:auto;padding:14px}
.mg h2{font-size:20px;margin:0 0 6px}.mg-b{font:inherit;font-size:16px;background:#FFF9F0;border:1px solid #fff;border-radius:12px;padding:8px 14px;min-height:42px;cursor:pointer;box-shadow:0 2px 0 #C9B28A;color:#4A3B3F;margin:3px}.mg-b:hover{background:#fff}.mg-b.go{background:#5FB37A;color:#fff}.mg-b.ok{background:#bfe6c9}.mg-b.no{background:#f5c6c0}
.mg-t{display:flex;gap:10px;align-items:center;background:#FFF9F0;border-radius:14px;padding:8px 10px;margin:8px 0;min-height:56px}.mg-t .face{font-size:30px}.mg-bar{height:10px;border-radius:99px;background:#E7D7B6;overflow:hidden;margin:6px 0}.mg-bar i{display:block;height:100%;background:#5FB37A;transition:width .3s}
.mg-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(120px,1fr));gap:8px}.mg input[type=range]{width:100%}.mg-card{background:#FFF9F0;border-radius:12px;padding:10px;text-align:center;box-shadow:0 2px 0 #C9B28A}.mg-big{font-size:46px;text-align:center}`;
let styled = false, root: HTMLElement | null = null;
const GAMES: { id: Subj; name: string; icon: string; blurb: string; run: (c: Ctx) => void }[] = [];
interface Ctx { box: HTMLElement; say: (t: string, good?: boolean) => void; done: (score: number, of: number) => void; progress: (n: number, of: number) => void }
const cheer = ["Wonderful!", "Yes! You've got it!", "Nice thinking!", "That's exactly right!", "Look at you go!"], coach = ["Not quite. Look again, you're close.", "Good try! Let's think it through together.", "Mistakes help your brain grow. Try the next one."];
function open(id: Subj | "menu", onClose?: () => void) {
  if (!styled) { styled = true; const s = document.createElement("style"); s.textContent = CSS; document.head.appendChild(s); }
  root ??= E("div", "mg", document.body); const R = root; R.innerHTML = ""; R.classList.add("show"); R.onkeydown = (e) => e.stopPropagation(); R.onpointerdown = (e) => e.stopPropagation();
  const P = E("div", "mg-p", R), close = () => { R.classList.remove("show"); R.innerHTML = ""; onClose?.(); }; R.onclick = (e) => { if (e.target === R) close(); };
  if (id === "menu") { E("h2", "", P, "🎮 Practice games"); E("div", "", P, "Pick one. Your teacher is rooting for you!"); const g = E("div", "mg-grid", P); for (const x of GAMES) { const c = E("button", "mg-b", g, `${x.icon} ${x.name}`); c.title = x.blurb; c.onclick = () => open(x.id, onClose); } E("button", "mg-b", P, "Close").onclick = close; return; }
  const G = GAMES.find((x) => x.id === id)!, T = TEACHER_BY_SUBJECT[id as keyof typeof TEACHER_BY_SUBJECT];
  E("h2", "", P, `${G.icon} ${G.name}`); const bar = E("div", "mg-bar", P), fill = E("i", "", bar); const teach = E("div", "mg-t", P), face = E("span", "face", teach, "🧑‍🏫"), line = E("div", "", teach, `${T?.name ?? "Your teacher"}: ${G.blurb}`); const box = E("div", "", P);
  const say = (t: string, good?: boolean) => { line.textContent = `${T?.first ?? "Teacher"}: ${t}`; face.textContent = good === true ? "🤩" : good === false ? "🤔" : "🧑‍🏫"; };
  const ctx: Ctx = { box, say, progress: (n, of) => { fill.style.width = `${(n / of) * 100}%`; },
    done: (score, of) => { box.innerHTML = ""; fill.style.width = "100%"; face.textContent = "🎉"; line.textContent = `${T?.first ?? "Teacher"}: ${score === of ? "Perfect! I'm so proud of you." : score >= of / 2 ? "Great work today. Keep it up!" : "Nice effort! Try again anytime, practice makes it easier."}`; E("div", "mg-big", box, `${score} / ${of}`); const r = E("div", "", box); r.style.textAlign = "center"; E("button", "mg-b go", r, "Play again").onclick = () => open(id, onClose); E("button", "mg-b", r, "More games").onclick = () => open("menu", onClose); E("button", "mg-b", r, "Done").onclick = close; Quests.track("game"); } };
  G.run(ctx); E("button", "mg-b", P, "Close").onclick = close;
}
const askMC = (c: Ctx, rounds: { q: () => HTMLElement | string; opts: string[]; ans: string; why?: string }[], after: (score: number) => void) => {
  let i = 0, score = 0; const next = () => {
    if (i >= rounds.length) { after(score); return; } c.progress(i, rounds.length); c.box.innerHTML = ""; const r = rounds[i]; const q = r.q(); if (typeof q === "string") E("div", "mg-big", c.box, q).style.fontSize = "26px"; else c.box.appendChild(q);
    const g = E("div", "mg-grid", c.box); let locked = false; for (const o of shuffle(r.opts)) { const b = E("button", "mg-b", g, o); b.onclick = () => { if (locked) return; locked = true; const ok = o === r.ans; b.classList.add(ok ? "ok" : "no"); if (!ok) Array.from(g.children).forEach((x) => { if (x.textContent === r.ans) x.classList.add("ok"); }); if (ok) score++; c.say(ok ? rnd(cheer) : `${rnd(coach)}${r.why ? " " + r.why : ""}`, ok); setTimeout(() => { i++; next(); }, ok ? 900 : 2200); }; }
  }; next();
};
/* ---- 1. Fraction Pizza ---- */
GAMES.push({ id: "math", name: "Fraction Pizza", icon: "🍕", blurb: "What fraction of the pizza is eaten? Count the slices.", run: (c) => {
  const rounds = Array.from({ length: 6 }, () => { const n = rnd([2, 3, 4, 5, 6, 8]), k = 1 + Math.floor(Math.random() * (n - 1)); const wrong = new Set<string>(); while (wrong.size < 3) { const a = 1 + Math.floor(Math.random() * n), b = rnd([2, 3, 4, 5, 6, 8]); if (`${a}/${b}` !== `${k}/${n}` && a < b) wrong.add(`${a}/${b}`); } return { q: () => { const w = E("div", "mg-big"); const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg"); svg.setAttribute("viewBox", "-52 -52 104 104"); svg.style.width = "150px"; for (let s = 0; s < n; s++) { const a0 = (s / n) * 6.2832 - 1.5708, a1 = ((s + 1) / n) * 6.2832 - 1.5708, p = document.createElementNS("http://www.w3.org/2000/svg", "path"); p.setAttribute("d", `M0 0 L${46 * Math.cos(a0)} ${46 * Math.sin(a0)} A46 46 0 0 1 ${46 * Math.cos(a1)} ${46 * Math.sin(a1)} Z`); p.setAttribute("fill", s < k ? "#E8D9B5" : "#F2A03D"); p.setAttribute("stroke", "#9A653D"); p.setAttribute("stroke-width", "2"); svg.appendChild(p); } w.appendChild(svg); E("div", "", w, "The pale slices are eaten. What fraction was eaten?").style.fontSize = "15px"; return w; }, opts: [`${k}/${n}`, ...wrong], ans: `${k}/${n}`, why: `The pizza has ${n} equal slices and ${k} are eaten, so ${k}/${n}.` }; });
  askMC(c, rounds, (s) => c.done(s, rounds.length)); } });
/* ---- 2. Seed Lab ---- */
GAMES.push({ id: "science", name: "Seed Lab", icon: "🌱", blurb: "Every plant likes different sun and water. Set the sliders to help it grow.", run: (c) => {
  const plants = [{ n: "Cactus 🌵", sun: 9, wat: 2 }, { n: "Fern 🌿", sun: 3, wat: 8 }, { n: "Sunflower 🌻", sun: 9, wat: 6 }, { n: "Mint 🍃", sun: 5, wat: 7 }, { n: "Tomato 🍅", sun: 8, wat: 5 }]; const set = shuffle(plants).slice(0, 4); let i = 0, score = 0;
  const next = () => { if (i >= set.length) { c.done(score, set.length); return; } c.progress(i, set.length); c.box.innerHTML = ""; const p = set[i]; let tries = 0; E("div", "mg-big", c.box, p.n); E("div", "", c.box, "Pick sunlight and water, then tap Grow. Hint: where does this plant live in nature?").style.textAlign = "center";
    const mk = (l: string) => { const w = E("div", "", c.box); E("div", "", w, l); const r = E("input", "", w) as HTMLInputElement; r.type = "range"; r.min = "0"; r.max = "10"; r.value = "5"; return r; }; const sun = mk("☀️ Sunlight"), wat = mk("💧 Water"); const out = E("div", "mg-big", c.box, "🌱"); const go = E("button", "mg-b go", c.box, "Grow!");
    go.onclick = () => { tries++; const ds = Math.abs(+sun.value - p.sun), dw = Math.abs(+wat.value - p.wat), d = ds + dw; out.textContent = d <= 2 ? "🌳" : d <= 4 ? "🌿" : d <= 7 ? "🥀" : "🪴"; if (d <= 2) { score += tries === 1 ? 1 : 0.5; c.say(`${rnd(cheer)} ${p.n.split(" ")[0]}s like about ${p.sun >= 7 ? "lots of" : "some"} sun and ${p.wat >= 7 ? "lots of" : p.wat <= 3 ? "very little" : "a medium amount of"} water.`, true); setTimeout(() => { i++; next(); }, 1800); } else c.say(`${ds > dw ? (+sun.value > p.sun ? "That's too much sun." : "It wants more sun.") : (+wat.value > p.wat ? "Too much water!" : "It's thirsty. Add water.")} Try again.`, false); }; };
  next(); } });
/* ---- 3. Timeline Sort ---- */
GAMES.push({ id: "history", name: "Timeline Sort", icon: "📜", blurb: "Put the events in order from oldest to newest.", run: (c) => {
  const sets: [string, number][][] = [[["Pyramids of Giza built", -2560], ["First Olympic Games", -776], ["Rome founded (legend)", -753], ["Columbus sails west", 1492], ["Declaration of Independence", 1776]], [["Printing press invented", 1440], ["Constitution signed", 1787], ["First airplane flight", 1903], ["Moon landing", 1969], ["World Wide Web begins", 1991]], [["Great Wall begun", -700], ["Writing invented in Sumer", -3200], ["Library of Alexandria founded", -285], ["Fall of Rome (West)", 476], ["Magna Carta", 1215]]];
  const s = rnd(sets), want = s.slice().sort((a, b) => a[1] - b[1]).map((x) => x[0]); let order = shuffle(s.map((x) => x[0])), tries = 0;
  const draw = () => { c.box.innerHTML = ""; E("div", "", c.box, "Tap ▲ ▼ to move events. Oldest at the top.").style.textAlign = "center"; order.forEach((n, i) => { const r = E("div", "mg-t", c.box); E("span", "", r, `${i + 1}.`); E("div", "", r, n).style.flex = "1"; const up = E("button", "mg-b", r, "▲"), dn = E("button", "mg-b", r, "▼"); up.onclick = () => { if (i > 0) { [order[i - 1], order[i]] = [order[i], order[i - 1]]; draw(); } }; dn.onclick = () => { if (i < order.length - 1) { [order[i + 1], order[i]] = [order[i], order[i + 1]]; draw(); } }; });
    E("button", "mg-b go", c.box, "Check").onclick = () => { tries++; const right = order.filter((n, i) => n === want[i]).length; c.progress(right, order.length); if (right === order.length) { c.say(`${rnd(cheer)} Every event is in the right place.`, true); setTimeout(() => c.done(tries === 1 ? 5 : tries === 2 ? 4 : 3, 5), 1500); } else c.say(`${right} of ${order.length} are in the right spot. Which one feels out of place?`, false); }; };
  draw(); } });
/* ---- 4. Word Builder ---- */
const WORDS = "act,age,air,all,and,ant,art,bad,bag,bat,bed,bee,big,bit,box,boy,bus,but,can,car,cat,cow,cup,cut,day,dig,dog,dot,ear,eat,egg,end,eye,fan,far,fat,fin,fix,fly,fun,gap,gas,get,god,got,gum,gym,hat,hen,her,him,hit,hop,hot,how,hug,ice,ink,jam,jar,job,joy,key,kid,kit,lab,lap,leg,let,lid,lip,log,lot,low,map,mix,mom,mud,mug,net,new,nod,not,nut,oak,odd,off,oil,old,one,our,out,owl,pan,pen,pet,pie,pig,pin,pot,pup,rat,raw,red,rib,rid,rip,rub,run,sad,say,sea,see,set,she,shy,sit,six,sky,sun,tag,tap,tea,ten,the,tie,tip,toe,top,toy,try,two,use,van,wag,war,was,wax,way,web,wet,who,why,win,yes,yet,you,zip,zoo,able,acid,also,area,army,baby,back,ball,band,bank,base,bath,bear,beat,bell,bird,blue,boat,body,bone,book,born,both,bowl,call,calm,came,camp,card,care,cart,case,cash,cave,city,clay,club,coat,cold,come,cook,cool,copy,corn,cost,crab,crew,crop,dark,date,dawn,deal,deep,desk,dish,door,down,draw,drop,drum,duck,dust,each,earn,east,easy,edge,face,fact,fair,fall,farm,fast,fear,feel,fire,fish,five,flag,flat,flow,fold,food,foot,form,four,free,from,fuel,full,gain,game,gift,girl,give,glad,goal,gold,good,grow,hair,half,hand,hard,have,head,hear,heat,help,here,hide,high,hill,hold,home,hope,horn,hour,idea,iron,jump,keep,kick,kind,king,knee,know,lake,lamp,land,last,late,lead,leaf,left,lend,less,life,lift,like,line,lion,list,live,load,long,look,loud,love,luck,made,mail,make,many,mark,meal,mean,meet,milk,mind,moon,more,most,move,much,name,near,neck,nest,next,nice,nine,noon,nose,note,once,only,open,over,page,pair,park,part,past,path,pick,pink,plan,play,plum,pool,poor,pull,push,rain,read,real,rest,rice,rich,ride,ring,road,rock,roll,roof,room,root,rope,rose,rule,safe,sail,salt,same,sand,save,seed,seem,self,sell,send,ship,shoe,shop,show,side,sing,skin,slow,snow,soft,some,song,soon,star,stay,step,stop,sure,swim,tail,take,talk,tall,team,tell,tent,test,than,that,them,then,they,thin,this,time,tiny,tool,town,tree,trip,true,turn,twin,under,unit,upon,very,view,walk,wall,want,warm,wash,wave,weak,wear,week,well,went,were,west,what,when,wide,wild,will,wind,wing,wish,with,wolf,wood,word,work,yard,year,zone,apple,beach,bread,brush,chair,clean,cloud,dance,dream,earth,field,flute,frog,grape,grass,green,happy,heart,horse,house,juice,light,lunch,music,night,ocean,paint,pizza,plant,queen,river,robot,smile,snake,space,sport,storm,sugar,table,tiger,train,water,whale,world,zebra".split(",");
GAMES.push({ id: "ela", name: "Word Builder", icon: "🔤", blurb: "Make real words from the letters. Longer words earn more stars!", run: (c) => {
  const set = new Set(WORDS), bases = ["planet", "garden", "flower", "monkey", "castle", "pirate", "rocket", "turtle", "pencil", "winter"]; const base = rnd(bases); const letters = shuffle(base.split("")); const found = new Set<string>(); let cur = "";
  const can = (w: string) => { const pool = letters.slice(); for (const ch of w) { const i = pool.indexOf(ch); if (i < 0) return false; pool.splice(i, 1); } return true; };
  const draw = () => { c.box.innerHTML = ""; c.progress(Math.min(found.size, 6), 6); const show = E("div", "mg-big", c.box, cur || "·"); void show; const g = E("div", "", c.box); g.style.textAlign = "center"; letters.forEach((ch, i) => { const b = E("button", "mg-b", g, ch.toUpperCase()); b.style.minWidth = "46px"; b.onclick = () => { cur += ch; b.disabled = true; show.textContent = cur.toUpperCase(); (b as any)._u = true; }; void i; });
    const r = E("div", "", c.box); r.style.textAlign = "center"; E("button", "mg-b", r, "Clear").onclick = () => { cur = ""; draw(); }; E("button", "mg-b go", r, "Check word").onclick = () => { if (cur.length < 3) { c.say("Words need at least 3 letters.", false); return; } if (found.has(cur)) { c.say("You already found that one!", false); } else if (can(cur) && set.has(cur)) { found.add(cur); c.say(`${rnd(cheer)} "${cur}" counts! ${cur.length >= 5 ? "A long one!" : ""}`, true); } else c.say("Hmm, I don't know that word. Try another.", false); cur = ""; draw(); if (found.size >= 6) setTimeout(() => c.done(6, 6), 900); };
    E("div", "", c.box, found.size ? "Found: " + [...found].join(", ") : "Find 6 words to finish.").style.textAlign = "center"; E("button", "mg-b", c.box, "I'm done").onclick = () => c.done(Math.min(6, found.size), 6); };
  c.say(`Hint: all the letters spell a secret word. Can you spot it? (${base.length} letters)`); draw(); } });
/* ---- 5. Needs & Wants budget ---- */
GAMES.push({ id: "life", name: "Needs or Wants?", icon: "🛒", blurb: "Sort the items and keep to your $20 budget.", run: (c) => {
  const items: [string, number, "need" | "want"][] = [["School lunch", 4, "need"], ["Bus fare home", 2, "need"], ["Notebook", 3, "need"], ["Warm coat", 12, "need"], ["Video game", 15, "want"], ["Candy bag", 3, "want"], ["Fancy sneakers", 18, "want"], ["Phone case", 8, "want"], ["Water bottle", 5, "need"], ["Toy robot", 10, "want"]];
  const rounds = shuffle(items).slice(0, 6).map(([n, p, k]) => ({ q: () => `${n}  ($${p})`, opts: ["Need", "Want"], ans: k === "need" ? "Need" : "Want", why: k === "need" ? `${n} is something you need to stay healthy, safe or learning.` : `${n} is fun, but you can live without it.` }));
  askMC(c, rounds, (s) => c.done(s, rounds.length)); } });
/* ---- 6. Career Match ---- */
GAMES.push({ id: "careers", name: "Career Match", icon: "🧑‍🔧", blurb: "Match the skill or tool to the job that uses it.", run: (c) => {
  const pairs: [string, string][] = [["Stethoscope", "Nurse or doctor"], ["Blueprints", "Architect"], ["Code on a computer", "Software developer"], ["Seeds and soil", "Farmer"], ["Microscope", "Scientist"], ["Courtroom", "Lawyer"], ["Camera and story", "Journalist"], ["Wrench and engine", "Mechanic"], ["Paint and canvas", "Artist"], ["Ledger of numbers", "Accountant"], ["Whistle and stopwatch", "Coach"], ["Hammer and saw", "Carpenter"]];
  const picks = shuffle(pairs).slice(0, 6), jobs = pairs.map((p) => p[1]);
  const rounds = picks.map(([t, a]) => ({ q: () => `Who uses: ${t}?`, opts: [a, ...shuffle(jobs.filter((j) => j !== a)).slice(0, 3)], ans: a, why: `${t} goes with ${a.toLowerCase()}.` }));
  askMC(c, rounds, (s) => c.done(s, rounds.length)); } });
export const openGames = (onClose?: () => void) => open("menu", onClose);
export const openGame = (id: Subj, onClose?: () => void) => open(id, onClose);
