/** Faculty (online-completable classes only): each teacher has fixed traits, five hairstyles and five outfits that rotate by weekday
 *  (a weekly shuffle, so nothing repeats Monday to Friday; weekends repeat Monday and Tuesday). Voice, tone, mannerisms and lines feed the classroom. */
import type { Look } from "./characters";
export interface Outfit { name: string; top: string; top_c: string; inner_c: string; bottom: string; bottom_c?: string; legs?: string; shoes_c: string; acc: string | null; accent_c?: string }
export interface HairDo { name: string; style: string; color: string; accent?: string; v?: string }
export interface Faculty {
  id: string; num: number; name: string; short: string; subject: string; room: string; age: number; gender: "F" | "M"; skin: string; eye: string; brow: string; build: { h: number; w: number };
  features: { glasses?: string; glassesColor?: string; earrings?: string; hoops?: boolean; beard?: string; beardColor?: string; freckles?: boolean; lines?: boolean };
  hair: HairDo[]; outfits: Outfit[]; makeup?: { lip: string }[]; mannerisms: string[]; tone: string; voice: { pitch: number; rate: number };
  lines: { greet: string; teach: string; praise: string; warn: string; bye: string };
}
const O = (name: string, top: string, top_c: string, inner_c: string, bottom: string, bottom_c: string | undefined, shoes_c: string, acc: string | null, accent_c?: string, legs?: string): Outfit => ({ name, top, top_c, inner_c, bottom, bottom_c, shoes_c, acc, accent_c, legs });
const H = (name: string, style: string, color: string, accent?: string, v?: string): HairDo => ({ name, style, color, accent, v });
export const FACULTY: Faculty[] = [
  { id: "tanaka", num: 110, name: "Mr. Hiroshi Tanaka", short: "Tanaka", subject: "Mathematics", room: "Room 112", age: 52, gender: "M", skin: "#E2B98F", eye: "#2A1C12", brow: "#4A4541", build: { h: .97, w: .92 },
    features: { glasses: "rect", glassesColor: "#3A3A3A", beard: "mustache", beardColor: "#5A5550", lines: true },
    hair: [H("Classic side part", "short", "#5E5A57"), H("Slicked back", "slick", "#55514E"), H("Short crop", "buzz", "#6A6663"), H("Tousled weekend", "pixie", "#5E5A57"), H("Side part, silver streak", "short", "#8A8683")],
    outfits: [O("Grey vest & navy tie", "vest", "#6B6E73", "#EEF2F5", "pants", "#2E3440", "#2A1C14", "tie", "#1F3A68"), O("Navy blazer & striped shirt", "blazer", "#23304A", "#DDE7F2", "pants", "#5B5F66", "#2A1C14", "tie", "#8C2F39"), O("Oatmeal cardigan & bow tie", "cardigan", "#CDBB9A", "#F6F3EC", "pants", "#4A4032", "#3B2A1E", "bowtie", "#2E5E4E"), O("Pale blue button-up", "buttonup", "#BFD4EA", "#BFD4EA", "pants", "#3C3F45", "#1E1E1E", "tie", "#2D2D2D"), O("Pi-day sweater", "sweater", "#2F5D50", "#2F5D50", "pants", "#34373D", "#1E1E1E", null)],
    mannerisms: ["Counts steps off on his fingers, always starting with the thumb", "Small precise nods while a student talks", "Straightens his tie before writing on the board", "Pauses mid-sentence to let a pun land, then smiles at nobody"],
    tone: "Calm, slow and soft-spoken. Speaks in numbered steps. Fond of terrible math puns delivered with total seriousness.", voice: { pitch: .85, rate: .82 },
    lines: { greet: "Good morning. Please be seated, and be rational.", teach: "Step one: isolate x. Step two: do not panic. Step three: check your work.", praise: "Excellent. That answer is... integral to the class.", warn: "I see a calculator under the desk. Its days are numbered.", bye: "Homework is problems one through twenty, odd only. Even you can do it." } },
  { id: "ayrissa", num: 111, name: "Ms. Ayrissa", short: "Ayrissa", subject: "English & Creative Writing", room: "Room 220", age: 36, gender: "F", skin: "#734633", eye: "#2A160E", brow: "#18100B", build: { h: 1, w: 1.03 },
    features: { freckles: true, earrings: "#D9D9D9", hoops: true },
    hair: [H("Honey-highlight boho curls", "curly", "#17110E", "#D8AE72"), H("Curly puff & orange headband", "afro", "#1E1510", "#F0651C", "puff"), H("Jet-black boho curls, middle part", "curly", "#120E0C"), H("Curtain-bang curls with honey pieces", "curly", "#17110E", "#D8AE72"), H("Shoulder-length honey twist-out", "curly", "#1C1410", "#C99A5E")],
    outfits: [O("Red kaftan top with gold embroidery", "sweater", "#A51F2E", "#A51F2E", "pants", "#2E3A55", "#1A1A1A", "beads", "#D9B45A"), O("Navy & white floral wrap dress", "dress", "#1E2A4A", "#1E2A4A", "none", undefined, "#E8E0D0", null, "#DCE6F2"), O("Stone cardigan & khaki joggers", "cardigan", "#BDB5A8", "#EDE8E0", "pants", "#C8B89A", "#F2F2F2", "lanyard", "#F0651C"), O("Tropical print wrap top & light denim", "sweater", "#ECE4D8", "#ECE4D8", "pants", "#8FA7C7", "#EDEDED", "beads", "#D98FA8"), O("Burnt-orange blazer & black tee", "blazer", "#C8561E", "#1C1C1C", "pants", "#232323", "#1A1A1A", "necklace", "#D4AF37")],
    makeup: [{ lip: "#7A3E34" }, { lip: "#8A4A3E" }, { lip: "#6E3A36" }, { lip: "#9A6A5A" }, { lip: "#5E1E2E" }],
    mannerisms: ["Rests her chin on her fist when she's really listening", "Her smile shows up before the answer does", "Flips her curls over one shoulder before reading a poem out loud", "Hypes up every raised hand: 'Yes! Say that!'"],
    tone: "High energy and warm. Talks fast, laughs easily and turns every answer into a celebration. Big on 'my brilliant people' and making sure every voice gets heard.", voice: { pitch: 1.18, rate: 1.14 },
    lines: { greet: "Good morning, my brilliant people! Pens out, energy up, let's WRITE!", teach: "A metaphor isn't decoration, it's a door. Open it! What's behind yours?", praise: "YES! Say that again, louder, for the people in the back!", warn: "Uh-uh, phones down. Your story is way more interesting than that screen.", bye: "Journal tonight, even one line. Your voice matters. Love you, bye!" } },
  { id: "okafor", num: 112, name: "Ms. Adaeze Okafor", short: "Okafor", subject: "Chemistry", room: "Lab 204", age: 38, gender: "F", skin: "#6B4226", eye: "#3B2314", brow: "#1A120D", build: { h: 1.06, w: .98 },
    features: { glasses: "cateye", glassesColor: "#7A1F2B", earrings: "#D4AF37" },
    hair: [H("Locs in a high bun", "bun", "#1B1411", "#D4AF37"), H("Waist-length box braids", "long", "#1B1411", "#D4AF37", "braids"), H("Natural afro", "afro", "#221815"), H("Sleek low ponytail", "pony", "#1B1411"), H("Burgundy twist-out", "curly", "#4A1C24")],
    outfits: [O("Lab coat over teal turtleneck", "labcoat", "#F4F6F6", "#1F6F6B", "pants", "#2B2D33", "#1C1C1C", null, "#1F6F6B"), O("Mustard blazer & cream blouse", "blazer", "#C99A2E", "#F2E8D5", "pants", "#3A2E28", "#5A3A22", "necklace", "#D4AF37"), O("Kente-trim wrap dress", "dress", "#1E4E79", "#1E4E79", "none", undefined, "#E0A526", "brooch", "#E0A526"), O("Emerald sweater & pencil skirt", "sweater", "#1F6A4A", "#1F6A4A", "skirt", "#2A2A2E", "#1C1C1C", "lanyard", "#C0392B", "#2A1A12"), O("Friday cardigan & periodic-table tee", "cardigan", "#6D2E46", "#ECECEC", "pants", "#4C6A92", "#F2F2F2", null)],
    makeup: [{ lip: "#8C3B3B" }, { lip: "#6E1E3A" }, { lip: "#9A4E3A" }, { lip: "#A0624A" }, { lip: "#9E1B22" }],
    mannerisms: ["Pushes her glasses up with one knuckle before making a point", "Taps a marker twice against her palm when waiting for an answer", "Raises one eyebrow instead of saying 'really?'", "Stands perfectly still, then moves with purpose"],
    tone: "Precise and dry. Short sentences, exact numbers, a deadpan joke about once a lesson. Never raises her voice; lowers it instead.", voice: { pitch: .95, rate: .92 },
    lines: { greet: "Goggles on, bags under the bench. Good morning.", teach: "Sodium plus water. Watch the reaction, not me. I already know what happens.", praise: "Correct, to three significant figures. I'm impressed.", warn: "That is not a beaker of juice. Put it down. Slowly.", bye: "Wash your hands. Twice. See you Thursday." } },
  { id: "obrien", num: 113, name: "Mr. Declan O'Brien", short: "O'Brien", subject: "History", room: "Room 301", age: 45, gender: "M", skin: "#F0C8AE", eye: "#5A7A4A", brow: "#8A3C1E", build: { h: 1, w: 1.14 },
    features: { beard: "full", beardColor: "#8A3C1E", freckles: true },
    hair: [H("Tousled copper", "pixie", "#9A4520"), H("Swept side part", "short", "#8A3C1E"), H("Tied-back 'historian bun'", "bun", "#8A3C1E"), H("Shoulder-length waves", "bob", "#9A4520"), H("Slicked for the museum trip", "slick", "#7A3418")],
    outfits: [O("Tweed blazer with elbow patches", "blazer", "#7A6A52", "#E8E2D4", "pants", "#4A4238", "#3B2616", "tie", "#5A2A1E"), O("Forest cardigan & plaid shirt", "cardigan", "#2F4A34", "#A6463A", "pants", "#6B5A44", "#3B2616", null), O("Burgundy sweater vest", "vest", "#6B1F2A", "#EDE8DC", "pants", "#3A3A3A", "#2A1A10", "bowtie", "#1F3A2A"), O("Rolled-sleeve oxford", "buttonup", "#E9E4D8", "#E9E4D8", "pants", "#556B45", "#3B2616", "tie", "#244060"), O("Cable-knit fisherman sweater", "turtleneck", "#DCD2BC", "#DCD2BC", "pants", "#3E3A33", "#3B2616", null)],
    mannerisms: ["Spreads both arms wide when setting a scene", "Leans in and drops to a stage whisper before a twist", "Strokes his beard while listening", "Rocks back on his heels after a punchline"],
    tone: "Theatrical storyteller. Big pauses, dramatic whispers, then a booming reveal. Treats every lesson like a campfire tale.", voice: { pitch: .75, rate: .95 },
    lines: { greet: "Gather round, gather round! Today... we march on Rome.", teach: "Picture it. 1066. Mud to your ankles. Arrows in the air. And then...", praise: "Ha! A scholar among us! Rome would have made you a senator.", warn: "Ah-ah. The only revolution in this room is on page forty.", bye: "History waits for no one. Except you, on Monday. Off with ye!" } },
  { id: "haddad", num: 114, name: "Mr. Karim Haddad", short: "Haddad", subject: "Geography & Careers", room: "CarryingCareers", age: 41, gender: "M", skin: "#B98460", eye: "#3A2412", brow: "#16100C", build: { h: 1.03, w: 1.02 },
    features: { beard: "full", beardColor: "#1A1410" },
    hair: [H("Neat short crop", "short", "#16100C"), H("Textured quiff", "slick", "#16100C"), H("Close buzz", "buzz", "#16100C"), H("Soft waves grown out", "pixie", "#1C1410"), H("Shaved clean", "bald", "#16100C")],
    outfits: [O("Olive field shirt", "buttonup", "#6A7048", "#6A7048", "pants", "#C8B68E", "#5A3A22", null), O("Navy sweater over collar", "sweater", "#23324E", "#EAEAEA", "pants", "#6A6258", "#3B2616", null), O("Charcoal suit & rust tie", "blazer", "#3A3C40", "#F2F2F2", "pants", "#3A3C40", "#1A1A1A", "tie", "#B0532E"), O("Camel cardigan", "cardigan", "#B8905A", "#2E4A5A", "pants", "#2E2E30", "#3B2616", null), O("Expedition vest", "vest", "#4A5A3A", "#D8CFC0", "pants", "#5A4E3A", "#5A3A22", "scarf", "#A83A2A")],
    mannerisms: ["Strokes his beard slowly before answering", "Points to places on an invisible map in the air", "Waits a full three seconds of silence for you to think", "Taps his compass watch when it's time to move on"],
    tone: "Patient, low and thoughtful. Asks more questions than he answers. Every sentence sounds like it has been considered twice.", voice: { pitch: .7, rate: .85 },
    lines: { greet: "Welcome, travelers. Where in the world shall we begin today?", teach: "A river does not choose the easy path. It chooses the downhill one. Why?", praise: "Good. You didn't just answer. You thought. That is the difference.", warn: "The map will still be here if you stop throwing it.", bye: "Look at the sky on your walk home. Tell me which way the wind blew." } },
  { id: "park", num: 115, name: "Ms. Chloe Park", short: "Park", subject: "Computer Science", room: "Lab 110", age: 27, gender: "F", skin: "#F1D1B5", eye: "#2A1A12", brow: "#1A1210", build: { h: .92, w: .94 },
    features: { glasses: "round", glassesColor: "#1A1A1A", earrings: "#7FD4E0" },
    hair: [H("Blunt bob with bangs", "bob", "#141014"), H("Space buns", "bun", "#141014", "#8E5CE0"), H("Lavender-streak ponytail", "pony", "#141014", "#B58CF0"), H("Long straight", "long", "#141014"), H("Teal-tipped pixie", "pixie", "#1E2A30")],
    outfits: [O("Oversized hoodie-sweater", "sweater", "#7A6AC8", "#7A6AC8", "skirt", "#2A2A34", "#F2F2F2", "lanyard", "#34C3A0", "#1E1E26"), O("Pastel cardigan & tee", "cardigan", "#F2B8C6", "#FFFFFF", "pants", "#4A6A9A", "#F2F2F2", "necklace", "#7FD4E0"), O("Pinafore dress", "dress", "#2E4A6A", "#F2F2F2", "none", undefined, "#1A1A1A", null, "#F2C84A", "#E8C8B0"), O("Hackathon track jacket", "track", "#1A1A24", "#34C3A0", "pants", "#1A1A24", "#34C3A0", "lanyard", "#34C3A0"), O("Mint button-up & suspender skirt", "buttonup", "#BFE8D8", "#BFE8D8", "skirt", "#3A3A4A", "#6A3A5A", "bowtie", "#6A3A5A", "#E8C8B0")],
    makeup: [{ lip: "#D0506A" }, { lip: "#C07080" }, { lip: "#D09088" }, { lip: "#B0606A" }, { lip: "#B8283A" }],
    mannerisms: ["Pushes her giant glasses up with the back of her wrist", "Fidgets with a keycap keychain while thinking", "Double thumbs-up when your code compiles", "Talks faster and faster until she catches herself, laughs, and restarts"],
    tone: "Quick, bubbly and nerdy. Lots of tech slang and tangents. Gets so excited she speeds up, then resets with a laugh.", voice: { pitch: 1.35, rate: 1.18 },
    lines: { greet: "Hi hi hi! Okay, log in, we're debugging today and it's gonna be SO fun.", teach: "So a loop is just the computer going 'again? again? again?' until you tell it to stop.", praise: "It compiled?! First try?! Double thumbs up, you legend.", warn: "Mm, that's an infinite loop. Your laptop is crying. Ctrl+C, please.", bye: "Commit your work! Push it! Don't be the person who loses it. Bye!" } },
  { id: "larsen", num: 116, name: "Dr. Ingrid Larsen", short: "Larsen", subject: "Biology", room: "Lab 206", age: 60, gender: "F", skin: "#F3D6C6", eye: "#4F86B8", brow: "#B8AE9E", build: { h: 1.02, w: 1 },
    features: { glasses: "round", glassesColor: "#B08A4A", lines: true, earrings: "#9FC9E0" },
    hair: [H("Silver chignon", "bun", "#D8D2C4"), H("Chin-length bob", "bob", "#E0DACE"), H("Crown braid updo", "bun", "#D8D2C4", "#9FC9E0"), H("Soft pixie", "pixie", "#E4DFD4"), H("Loose silver waves", "long", "#D0C9BA")],
    outfits: [O("Lab coat over lavender blouse", "labcoat", "#F7F7F5", "#B9A6D6", "skirt", "#4A4E5A", "#3A2E28", "lanyard", "#2E7D5B", "#D8B8A8"), O("Moss cardigan", "cardigan", "#6A7F4A", "#F2EEE4", "pants", "#5A4E40", "#3A2E28", "brooch", "#C9A13B"), O("Botanical print dress", "dress", "#2E5E6A", "#2E5E6A", "none", undefined, "#2A2A2A", "necklace", "#E7C66A", "#D8B8A8"), O("Fair Isle sweater", "sweater", "#9C3B3B", "#9C3B3B", "pants", "#2E3A4A", "#3A2E28", null, "#F2EEE4"), O("Field-trip vest & flannel", "vest", "#8A7A5A", "#3E6A8A", "pants", "#4A4A3A", "#5A3A22", "scarf", "#C9763B")],
    makeup: [{ lip: "#C07A7A" }, { lip: "#D0705A" }, { lip: "#9A5A6A" }, { lip: "#C8908A" }, { lip: "#B02A36" }],
    mannerisms: ["Peers over her glasses before asking a question she already knows the answer to", "Holds up one finger: 'Ah, but...'", "Cups her hands as if holding something alive when describing cells", "Hums while she labels specimen jars"],
    tone: "Warm, grandmotherly and razor sharp. Unhurried and kind, with a Scandinavian bluntness that surprises people.", voice: { pitch: 1.05, rate: .85 },
    lines: { greet: "Good morning, little organisms. Let us see what's alive today.", teach: "Ah, but... why does the cell bother? Everything in nature is a bargain.", praise: "Very good. You think like a scientist now. Dangerous.", warn: "The frog has been through enough. Please stop waving it.", bye: "Go outside. Look at a leaf. That is your homework, and I will check." } },
  { id: "raman", num: 117, name: "Mrs. Priya Raman", short: "Raman", subject: "English Literature", room: "Room 215", age: 44, gender: "F", skin: "#A8703F", eye: "#2A160C", brow: "#1C120C", build: { h: .95, w: .97 },
    features: { glasses: "half", glassesColor: "#6A4A8A", earrings: "#E6C35C" },
    hair: [H("Long center-part", "long", "#16100C"), H("Low braided bun", "bun", "#16100C", "#E6C35C"), H("Single long braid", "pony", "#1A120E", "#B83A5A"), H("Soft shoulder waves", "bob", "#24160F"), H("Loose curls, henna tint", "curly", "#4A2418")],
    outfits: [O("Plum cardigan & floral blouse", "cardigan", "#5E2E5A", "#F2D8C8", "skirt", "#2E2A40", "#3A2418", "scarf", "#D9A441", "#6B4428"), O("Saffron kurta dress", "dress", "#D98E2B", "#D98E2B", "none", undefined, "#8A1F3A", "necklace", "#8A1F3A"), O("Teal turtleneck & long skirt", "turtleneck", "#1E6A70", "#1E6A70", "skirt", "#5A4632", "#2A1A12", "necklace", "#E6C35C", "#5A4632"), O("Rose blazer & ivory shell", "blazer", "#C77A8A", "#F5EFE6", "pants", "#3B3346", "#E6C35C", "brooch", "#E6C35C"), O("Book-club sweater", "sweater", "#8A9A5B", "#8A9A5B", "skirt", "#4A3A2A", "#2A1A12", "scarf", "#B83A5A", "#3A2A20")],
    makeup: [{ lip: "#9A4A5A" }, { lip: "#8A5060" }, { lip: "#8E2A3A" }, { lip: "#8A3A2A" }, { lip: "#9A6458" }],
    mannerisms: ["Hugs her book to her chest when a passage moves her", "Tilts her head and smiles before gently disagreeing", "Looks over her half-moon glasses at the whole room", "Quotes a line of poetry to end almost any argument"],
    tone: "Gentle, lyrical and encouraging. Long, flowing sentences, lots of 'dear' and 'lovely'. Corrects you so kindly you thank her for it.", voice: { pitch: 1.1, rate: .88 },
    lines: { greet: "Good morning, my dears. Open your books to where the story left us.", teach: "Notice how the rain falls just as she says goodbye. Nothing in a novel is an accident.", praise: "Oh, that's lovely. Write that down before it flies away.", warn: "Darling, 'it was good' is not an essay. Tell me why it was good.", bye: "Read chapter nine tonight, and let it keep you up a little." } },
];
const hashStr = (s: string) => { let h = 2166136261; for (const ch of s) { h ^= ch.charCodeAt(0); h = Math.imul(h, 16777619); } return h >>> 0; };
const rng = (seed: number) => () => { seed = (seed + 0x6d2b79f5) >>> 0; let t = seed; t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296; };
const weekKey = (d: Date) => { const j = new Date(d.getFullYear(), 0, 1), w = Math.floor((+d - +j) / 864e5 / 7); return `${d.getFullYear()}-${w}`; };
/** index 0..4 for this day: a weekly shuffle per teacher and per kind (hair vs outfit); Sat = Mon's pick, Sun = Tue's */
export function dayIndex(id: string, kind: string, d = new Date()) {
  const r = rng(hashStr(id + kind + weekKey(d))), perm = [0, 1, 2, 3, 4]; for (let i = 4; i > 0; i--) { const j = Math.floor(r() * (i + 1)); [perm[i], perm[j]] = [perm[j], perm[i]]; }
  const wd = d.getDay(), slot = wd === 6 ? 0 : wd === 0 ? 1 : wd - 1; return perm[slot];
}
const STYLE: Record<string, string> = { short: "crop", slick: "crop", pixie: "crop", buzz: "buzz", bun: "bun", bob: "bob", long: "long", pony: "pony", afro: "afro", curly: "curly", bald: "bald" };
const GLASS: Record<string, string> = { rect: "square", round: "round", cateye: "cat", half: "half" };
export function facultyLook(t: Faculty, d = new Date()): Look {
  const hd = t.hair[dayIndex(t.id, "hair", d)], of = t.outfits[dayIndex(t.id, "outfit", d)], F = t.features, mk = t.makeup?.[dayIndex(t.id, "makeup", d)];
  const look: Look = {
    id: t.num, age: "adult", skin: t.skin, hair: hd.color, hair2: hd.accent && hd.style !== "afro" ? hd.accent : undefined, style: STYLE[hd.style] ?? "crop", shirt: of.top_c, shirt2: of.inner_c, top: of.top, bottom: of.bottom === "none" ? "pants" : of.bottom,
    pants: of.bottom_c ?? "#3a3a44", tights: of.legs, shoes: of.shoes_c, acc: of.acc ?? undefined, accent: of.accent_c, eyeColor: t.eye, browColor: t.brow, brow: t.gender === "M" ? "thick" : "soft",
    glasses: F.glasses ? GLASS[F.glasses] ?? "round" : false, glassColor: F.glassesColor, earrings: F.earrings, hoops: F.hoops, beard: F.beard, beardColor: F.beardColor, freckles: F.freckles, lines: F.lines || t.age > 50,
    bodyW: t.build.w, hScale: t.build.h, lip: mk?.lip, lanyard: of.acc === "lanyard", tag: false,
  };
  if (hd.style === "afro" && hd.accent) { look.hat = "headband"; look.hatColor = hd.accent; }
  return look;
}
export const FACULTY_BY_ID: Record<string, Faculty> = Object.fromEntries(FACULTY.map((f) => [f.id, f]));
