/** What is trending right now, by age group: music, fashion, hobbies, games, shows and slang. Kids talk about these the way real kids do.
 *  The built-in list is a snapshot; drop a `trends.json` next to the game (same shape) to update it without touching code. It also rotates weekly so chats stay fresh. */
import type { Age } from "./characters";
export type TrendKind = "music" | "fashion" | "hobby" | "game" | "show" | "sport" | "slang";
export type Band = "k2" | "g35" | "g68" | "hs";
export const TRENDS_AS_OF = "2025";
type Bank = Record<Band, Partial<Record<TrendKind, string[]>>>;
let BANK: Bank = {
  k2: { music: ["the Bluey songs", "baby shark remixes", "the 'Let It Go' song", "silly dance songs"], fashion: ["light-up shoes", "rainbow everything", "sparkly hair clips", "dinosaur backpacks"], hobby: ["building with blocks", "sticker books", "playing tag", "making slime", "bubble blowing"], game: ["Minecraft Pocket Edition", "Pokémon", "Mario"], show: ["Bluey", "Paw Patrol", "Gabby's Dollhouse", "dinosaur shows"], sport: ["kickball", "jump rope", "scooters"], slang: ["super duper", "so silly", "that's epic"] },
  g35: { music: ["pop songs from Taylor Swift's eras", "movie soundtrack songs", "K-pop dances", "ukulele songs"], fashion: ["friendship bracelets", "scrunchies", "squishmallow clips", "colorful sneakers", "charm bracelets"], hobby: ["Pokémon cards", "loom bands", "drawing manga characters", "slime and squishies", "LEGO sets", "skateboarding"], game: ["Minecraft", "Roblox", "Mario Kart", "Pokémon", "Fortnite for the older cousins"], show: ["anime like Demon Slayer", "Wednesday", "Marvel movies", "YouTube challenge videos"], sport: ["soccer", "gymnastics", "pickleball", "swim team"], slang: ["no cap", "that's so cool", "I'm dying", "sus"] },
  g68: { music: ["Taylor Swift", "Olivia Rodrigo", "Sabrina Carpenter", "K-pop like Stray Kids and NewJeans", "Billie Eilish", "lo-fi beats while studying"], fashion: ["baggy cargo pants", "chunky sneakers", "oversized hoodies", "friendship bracelets", "Stanley-style tumblers", "charm necklaces"], hobby: ["making playlists", "crochet", "pickleball", "journaling", "editing short videos", "thrifting", "baking trends"], game: ["Roblox", "Minecraft", "Fortnite", "Among Us", "Stardew Valley"], show: ["anime", "Wednesday", "Stranger Things", "cooking videos", "short-form videos"], sport: ["basketball", "volleyball", "track", "skateboarding"], slang: ["no cap", "lowkey", "that's so real", "I can't even", "bet", "it's giving"] },
  hs: { music: ["Chappell Roan", "Sabrina Carpenter", "Taylor Swift's whole discography", "Tyler, the Creator", "Bad Bunny", "Kendrick Lamar", "indie playlists", "K-pop"], fashion: ["thrifted denim", "baggy jeans", "vintage band tees", "platform sneakers", "layered jewelry", "bucket hats", "oversized blazers"], hobby: ["film photography", "thrifting and upcycling", "making zines", "coding side projects", "bouldering", "pottery", "journaling", "learning guitar", "baking sourdough"], game: ["Minecraft", "Valorant", "Stardew Valley", "Balatro", "Zelda", "Fortnite"], show: ["A24 movies", "anime", "true-crime podcasts", "Wednesday", "The Bear", "short-form videos"], sport: ["pickleball", "track and field", "volleyball", "basketball", "bouldering"], slang: ["that's so real", "I'm cooked", "no cap", "lowkey", "it's giving", "bet", "touch grass", "I'm dead"] },
};
export const loadTrends = async () => { try { const r = await fetch("trends.json", { cache: "no-cache" }); if (r.ok) { const j = await r.json(); if (j && typeof j === "object") BANK = { ...BANK, ...j }; } } catch { /* offline: built-in list */ } };
const week = () => Math.floor(Date.now() / (7 * 864e5));
export const bandOf = (a: Age | string | undefined): Band => (a === "k2" || a === "g35" || a === "g68" ? a : "hs");
/** a trend of a kind for this age group; rotates weekly, offset per person so two kids don't always pick the same one */
export function trendOf(band: Band, kind: TrendKind, seed: number): string | null { const a = BANK[band]?.[kind]; if (!a?.length) return null; return a[(week() + seed) % a.length]; }
/** which kind of trend fits an interest word */
export function kindFor(interest: string): TrendKind { const t = interest.toLowerCase(); if (/soccer|basket|volley|swim|track|gym|sport|skate|pickle|run|dance team|boulder/.test(t)) return "sport"; if (/music|piano|violin|guitar|sing|band|playlist|dj/.test(t)) return "music"; if (/game|minecraft|robot|cod|chess|puzzle/.test(t)) return "game"; if (/fashion|style|draw|paint|art|photo|design/.test(t)) return "fashion"; if (/anime|movie|film|show|theater|read|book|manga/.test(t)) return "show"; return "hobby"; }
export const slangFor = (band: Band, seed: number) => trendOf(band, "slang", seed) ?? "for real";
