/** VR field trips: five fully 3D places you stand inside and look around (drag, tilt your phone, or use a headset / cardboard viewer).
 *  Look at a glowing spot (hold your gaze, or tap it) and the guide teacher tells you about it, with a moving mouth and captions.
 *  Everything is built from simple shapes, so there are no big downloads. */
import * as THREE from "three";
import { StereoEffect } from "three/examples/jsm/effects/StereoEffect.js";
import { drawChar } from "../hall3d/rig";
import { TEACHER_BY_SUBJECT } from "../hall3d/roster";
export interface Spot { at: [number, number, number]; title: string; fact: string }
export interface Trip { id: string; name: string; icon: string; subject: "science" | "history"; blurb: string; sky: [string, string]; fog: string; build: (g: THREE.Group, t: Tick[]) => void; spots: Spot[] }
type Tick = (time: number, dt: number) => void;
const M = (c: string, o: Partial<THREE.MeshStandardMaterialParameters> = {}) => new THREE.MeshStandardMaterial({ color: c, roughness: 0.85, ...o });
const mesh = (geo: THREE.BufferGeometry, mat: THREE.Material, x = 0, y = 0, z = 0) => { const m = new THREE.Mesh(geo, mat); m.position.set(x, y, z); return m; };
const rr = (a: number, b: number) => a + Math.random() * (b - a);
const ring = (n: number, r: number, f: (a: number, i: number) => void) => { for (let i = 0; i < n; i++) f((i / n) * Math.PI * 2, i); };
export const TRIPS: Trip[] = [
  { id: "reef", name: "Coral Reef", icon: "🐠", subject: "science", blurb: "Dive into warm, shallow water full of life.", sky: ["#BFEFFF", "#0E5C9C"], fog: "#2A8FC0",
    build: (g, t) => { g.add(mesh(new THREE.CircleGeometry(60, 40).rotateX(-Math.PI / 2), M("#E8D7A8"), 0, -2.2, 0));
      ring(26, 12, (a, i) => { const r = rr(6, 20), c = ["#F26B5B", "#F2A03D", "#E070A8", "#8E7CC3", "#FFD23F"][i % 5], cl = new THREE.Group(); for (let k = 0; k < 4; k++) cl.add(mesh(new THREE.ConeGeometry(rr(0.2, 0.5), rr(1, 2.4), 8), M(c), rr(-0.5, 0.5), rr(-1.8, -1), rr(-0.5, 0.5))); cl.position.set(Math.cos(a) * r, 0, Math.sin(a) * r); g.add(cl); });
      for (let s = 0; s < 4; s++) { const sch: THREE.Mesh[] = []; for (let i = 0; i < 9; i++) { const f = new THREE.Group(); f.add(mesh(new THREE.SphereGeometry(0.22, 8, 6).scale(1.6, 1, 0.6), M(["#FF8A3D", "#FFD23F", "#7BD3F2", "#F26B8D"][s]))); f.add(mesh(new THREE.ConeGeometry(0.16, 0.3, 4).rotateZ(Math.PI / 2), M(["#FF8A3D", "#FFD23F", "#7BD3F2", "#F26B8D"][s]), -0.36, 0, 0)); g.add(f); sch.push(f as any); }
        const rad = 5 + s * 2.2, h = -0.4 + s * 0.5, sp = 0.35 + s * 0.08; t.push((time) => sch.forEach((f, i) => { const a = time * sp + i * 0.35 + s; f.position.set(Math.cos(a) * rad, h + Math.sin(time + i) * 0.2, Math.sin(a) * rad); f.rotation.y = -a; })); }
      const tu = new THREE.Group(); tu.add(mesh(new THREE.SphereGeometry(0.7, 12, 8).scale(1.3, 0.55, 1), M("#6B9B4C"))); tu.add(mesh(new THREE.SphereGeometry(0.22, 8, 6), M("#8BBF6A"), 0.95, 0.05, 0)); g.add(tu); t.push((time) => { const a = time * 0.12; tu.position.set(Math.cos(a) * 9, 1.4 + Math.sin(time * 0.5) * 0.3, Math.sin(a) * 9); tu.rotation.y = -a + Math.PI; });
      const bub: THREE.Mesh[] = []; for (let i = 0; i < 40; i++) { const b = mesh(new THREE.SphereGeometry(0.06, 6, 4), new THREE.MeshBasicMaterial({ color: "#fff", transparent: true, opacity: 0.6 }), rr(-9, 9), rr(-2, 6), rr(-9, 9)); g.add(b); bub.push(b); } t.push((_, dt) => bub.forEach((b) => { b.position.y += dt * 0.6; if (b.position.y > 7) b.position.y = -2; })); },
    spots: [{ at: [-5, 1.2, -6], title: "Coral is an animal", fact: "Coral looks like a plant or a rock, but it is made of tiny animals called polyps. Thousands live together, and reefs cover less than one percent of the ocean floor yet shelter about a quarter of sea life." }, { at: [6, 2, -3], title: "Schooling fish", fact: "Fish swim in schools to stay safe. With so many eyes, it is hard for a hungry predator to sneak up. Every fish copies its neighbours, so the whole group turns together like one big animal." }, { at: [0, 3, 9], title: "Sea turtle", fact: "Sea turtles can hold their breath for hours while resting. They return to the same beach where they were born to lay their own eggs, sometimes after travelling thousands of kilometres." }] },
  { id: "forest", name: "Rainforest", icon: "🌴", subject: "science", blurb: "Tall trees, butterflies and a river below the canopy.", sky: ["#E6FFD0", "#2E7D4F"], fog: "#3B8F5E",
    build: (g, t) => { g.add(mesh(new THREE.CircleGeometry(60, 40).rotateX(-Math.PI / 2), M("#5B4A2B"), 0, -1.6, 0)); const rv = mesh(new THREE.PlaneGeometry(4, 60).rotateX(-Math.PI / 2), M("#4FA3C0", { roughness: 0.2 }), 6, -1.55, 0); g.add(rv);
      for (let i = 0; i < 46; i++) { const a = rr(0, 6.28), r = rr(5, 28), h = rr(10, 20), tr = new THREE.Group(); tr.add(mesh(new THREE.CylinderGeometry(0.35, 0.55, h, 8), M("#6B4A2B"), 0, h / 2 - 1.6, 0)); tr.add(mesh(new THREE.SphereGeometry(rr(2.5, 4.5), 8, 6).scale(1, 0.5, 1), M(["#2F9E5B", "#3FB06B", "#1F7A44"][i % 3]), 0, h - 1.4, 0)); tr.position.set(Math.cos(a) * r, 0, Math.sin(a) * r); g.add(tr); }
      for (let i = 0; i < 14; i++) { const w = new THREE.Group(); const c = ["#FFB347", "#6AA9F0", "#F26B8D"][i % 3]; w.add(mesh(new THREE.PlaneGeometry(0.35, 0.28), new THREE.MeshBasicMaterial({ color: c, side: THREE.DoubleSide }), -0.18, 0, 0)); w.add(mesh(new THREE.PlaneGeometry(0.35, 0.28), new THREE.MeshBasicMaterial({ color: c, side: THREE.DoubleSide }), 0.18, 0, 0)); g.add(w); const R = rr(3, 10), ph = rr(0, 6); t.push((time) => { const a = time * 0.3 + ph; w.position.set(Math.cos(a) * R, 1 + Math.sin(time * 1.3 + ph) * 0.8, Math.sin(a) * R); w.children.forEach((c, k) => (c.rotation.y = Math.sin(time * 14 + ph) * (k ? -0.8 : 0.8))); }); } },
    spots: [{ at: [-4, 3, -7], title: "The canopy", fact: "The top layer of the rainforest is called the canopy. The leaves are so thick that very little sunlight reaches the ground, and many animals spend their whole lives up there without ever touching the forest floor." }, { at: [5, 1.4, 4], title: "Rainforest river", fact: "Rainforests make their own rain. Trees release water vapour from their leaves, which rises, cools into clouds and falls again. Rivers carry that water back through the forest." }, { at: [0, 4, -12], title: "Butterflies", fact: "Butterflies taste with their feet and drink nectar through a long straw called a proboscis. Bright wing colours can warn birds that a butterfly tastes bad." }] },
  { id: "rome", name: "Ancient Rome", icon: "🏛️", subject: "history", blurb: "Walk through the Roman Forum, 2,000 years ago.", sky: ["#FFE9C2", "#7FB4E8"], fog: "#EBD9B5",
    build: (g, t) => { g.add(mesh(new THREE.CircleGeometry(60, 40).rotateX(-Math.PI / 2), M("#E9DEC4"), 0, -1.6, 0)); g.add(mesh(new THREE.RingGeometry(4, 5, 48).rotateX(-Math.PI / 2), M("#B04A3C"), 0, -1.58, 0));
      ring(14, 11, (a) => { const c = new THREE.Group(); c.add(mesh(new THREE.CylinderGeometry(0.55, 0.65, 7, 14), M("#F4EFE6"), 0, 1.9, 0)); c.add(mesh(new THREE.BoxGeometry(1.7, 0.4, 1.7), M("#E3DCCB"), 0, 5.5, 0)); c.add(mesh(new THREE.BoxGeometry(1.7, 0.35, 1.7), M("#E3DCCB"), 0, -1.45, 0)); c.position.set(Math.cos(a) * 11, 0, Math.sin(a) * 11); g.add(c); });
      const arch = new THREE.Group(); arch.add(mesh(new THREE.BoxGeometry(2, 9, 2), M("#E8DCC0"), -4, 2.9, 0)); arch.add(mesh(new THREE.BoxGeometry(2, 9, 2), M("#E8DCC0"), 4, 2.9, 0)); arch.add(mesh(new THREE.BoxGeometry(10, 2, 2), M("#E8DCC0"), 0, 7.5, 0)); arch.position.set(0, 0, -20); g.add(arch);
      ring(8, 14, (a, i) => { const f = mesh(new THREE.PlaneGeometry(1.2, 3), new THREE.MeshBasicMaterial({ color: i % 2 ? "#B04A3C" : "#C79B2E", side: THREE.DoubleSide }), Math.cos(a) * 9, 4, Math.sin(a) * 9); f.lookAt(0, 4, 0); g.add(f); t.push((time) => { f.rotation.z = Math.sin(time * 1.5 + i) * 0.08; }); }); },
    spots: [{ at: [-8, 3, 6], title: "Roman columns", fact: "Roman builders copied Greek columns and added arches and concrete. A Roman arch spreads weight to the sides so buildings could be taller and last longer. Many Roman buildings still stand today." }, { at: [0, 6, -18], title: "The triumphal arch", fact: "Arches like this celebrated victories and important leaders. Generals paraded beneath them while crowds cheered. The carvings told the story of the event for everyone to read." }, { at: [8, 2.5, 5], title: "The Forum", fact: "The Forum was the busy centre of Rome. People met friends, shopped, listened to speeches and watched trials. It was part town square, part courthouse and part marketplace." }] },
  { id: "space", name: "Space Station", icon: "🛰️", subject: "science", blurb: "Float above the Earth as it spins below.", sky: ["#02030A", "#0A0D26"], fog: "#02030A",
    build: (g, t) => { const st = new THREE.Group(); for (let i = 0; i < 700; i++) { const s = mesh(new THREE.SphereGeometry(0.06, 4, 3), new THREE.MeshBasicMaterial({ color: "#fff" })); const a = rr(0, 6.28), b = rr(-1.4, 1.4), r = 80; s.position.set(Math.cos(a) * Math.cos(b) * r, Math.sin(b) * r, Math.sin(a) * Math.cos(b) * r); st.add(s); } g.add(st);
      const cv = document.createElement("canvas"); cv.width = 512; cv.height = 256; const c = cv.getContext("2d")!; c.fillStyle = "#1E5FA8"; c.fillRect(0, 0, 512, 256); c.fillStyle = "#4C9F5E"; for (let i = 0; i < 40; i++) { c.beginPath(); c.ellipse(rr(0, 512), rr(20, 236), rr(14, 50), rr(8, 28), rr(0, 3), 0, 6.28); c.fill(); } c.fillStyle = "rgba(255,255,255,.55)"; for (let i = 0; i < 30; i++) { c.beginPath(); c.ellipse(rr(0, 512), rr(0, 256), rr(20, 60), rr(4, 10), 0, 0, 6.28); c.fill(); }
      const earth = mesh(new THREE.SphereGeometry(22, 48, 32), new THREE.MeshStandardMaterial({ map: new THREE.CanvasTexture(cv), roughness: 0.9 }), 0, -30, -10); g.add(earth); t.push((time) => { earth.rotation.y = time * 0.03; });
      const ringG = new THREE.Group(); const rm = M("#D8DCE6", { metalness: 0.5, roughness: 0.4 }); ringG.add(mesh(new THREE.TorusGeometry(7, 0.45, 8, 40), rm)); for (let i = 0; i < 4; i++) { const a = (i / 4) * 6.28; ringG.add(mesh(new THREE.BoxGeometry(0.2, 7, 0.2), rm, Math.cos(a) * 3.5, Math.sin(a) * 3.5, 0)); } ringG.position.set(0, 3, -12); ringG.rotation.x = 1.2; g.add(ringG); t.push((time) => { ringG.rotation.z = time * 0.15; });
      const sp = new THREE.Group(); sp.add(mesh(new THREE.BoxGeometry(0.4, 0.4, 3), rm)); for (const sx of [-1, 1]) sp.add(mesh(new THREE.BoxGeometry(4, 0.05, 1.6), M("#27408B", { metalness: 0.3 }), sx * 2.4, 0, 0)); sp.position.set(6, 1, 2); g.add(sp); t.push((time) => { sp.rotation.y = time * 0.2; sp.position.y = 1 + Math.sin(time * 0.6) * 0.3; }); },
    spots: [{ at: [0, 0, -30], title: "Planet Earth", fact: "From orbit, Earth looks like a glowing blue marble. You can see weather systems, oceans and city lights at night. Astronauts say it changes how they think about home." }, { at: [0, 3, -12], title: "The space station", fact: "The International Space Station travels at about 28,000 kilometres an hour and circles the Earth every 90 minutes. Astronauts see 16 sunrises and sunsets every day." }, { at: [6, 1, 2], title: "Solar panels", fact: "Big solar panels turn sunlight into electricity for the station. In space there is no air to block the sun, so the panels make plenty of power for lights, computers and experiments." }] },
  { id: "dino", name: "Dino Valley", icon: "🦕", subject: "science", blurb: "A valley from 150 million years ago.", sky: ["#FFE6B0", "#E8845A"], fog: "#F0B98A",
    build: (g, t) => { g.add(mesh(new THREE.CircleGeometry(70, 40).rotateX(-Math.PI / 2), M("#7A8F4A"), 0, -1.6, 0)); const vo = mesh(new THREE.ConeGeometry(14, 22, 20), M("#5A4636"), -22, 9, -34); g.add(vo); g.add(mesh(new THREE.SphereGeometry(2.4, 12, 8), new THREE.MeshBasicMaterial({ color: "#FF6A2B" }), -22, 20, -34)); const emb: THREE.Mesh[] = []; for (let i = 0; i < 30; i++) { const e = mesh(new THREE.SphereGeometry(0.25, 6, 4), new THREE.MeshBasicMaterial({ color: "#FF9A3D" }), -22, 20, -34); (e as any).v = [rr(-3, 3), rr(3, 8), rr(-3, 3)]; g.add(e); emb.push(e); } t.push((_, dt) => emb.forEach((e) => { const v = (e as any).v; e.position.x += v[0] * dt; e.position.y += v[1] * dt - dt * 3 * ((e.position.y - 20) * 0.1 + 1) * 0.2; e.position.z += v[2] * dt; if (e.position.y > 34 || e.position.y < 5) e.position.set(-22, 20, -34); }));
      for (let i = 0; i < 30; i++) { const f = new THREE.Group(); for (let k = 0; k < 5; k++) f.add(mesh(new THREE.ConeGeometry(0.12, 2, 4).rotateZ(rr(-0.7, 0.7)), M("#3E9B4F"), rr(-0.4, 0.4), 0, rr(-0.4, 0.4))); const a = rr(0, 6.28), r = rr(5, 26); f.position.set(Math.cos(a) * r, -0.6, Math.sin(a) * r); g.add(f); }
      const bro = new THREE.Group(); const sk = M("#8B9A6B"); bro.add(mesh(new THREE.SphereGeometry(2.2, 14, 10).scale(1.6, 1, 1), sk, 0, 3.2, 0)); bro.add(mesh(new THREE.CylinderGeometry(0.5, 0.9, 5, 10), sk, 3.2, 5.4, 0).rotateZ(-0.5)); bro.add(mesh(new THREE.SphereGeometry(0.7, 10, 8), sk, 5.1, 7.9, 0)); for (const [x, z] of [[-1.6, -1], [-1.6, 1], [1.6, -1], [1.6, 1]]) bro.add(mesh(new THREE.CylinderGeometry(0.5, 0.45, 3.4, 8), sk, x, 1.1, z)); bro.add(mesh(new THREE.ConeGeometry(0.8, 5, 8).rotateZ(Math.PI / 2), sk, -5.2, 3.2, 0)); bro.position.set(10, -1.6, -8); bro.rotation.y = 0.5; g.add(bro); t.push((time) => { bro.position.y = -1.6 + Math.abs(Math.sin(time * 0.8)) * 0.08; });
      const pt: THREE.Group[] = []; for (let i = 0; i < 3; i++) { const p = new THREE.Group(); p.add(mesh(new THREE.ConeGeometry(0.4, 1.8, 4).rotateZ(Math.PI / 2), M("#C06A4A"), 0, 0, 0)); p.add(mesh(new THREE.BoxGeometry(0.1, 0.02, 3.2), M("#C98B6A"), 0, 0, 0)); g.add(p); pt.push(p); } t.push((time) => pt.forEach((p, i) => { const a = time * 0.25 + i * 2.1; p.position.set(Math.cos(a) * 12, 9 + i * 1.5 + Math.sin(time + i) * 0.6, Math.sin(a) * 12); p.rotation.y = -a; p.children[1].rotation.z = Math.sin(time * 3 + i) * 0.3; })); },
    spots: [{ at: [10, 4, -8], title: "A long-necked giant", fact: "Giants like Brachiosaurus ate plants all day, up to hundreds of kilograms. Their long necks let them reach leaves high in the trees that shorter dinosaurs could not." }, { at: [-22, 22, -34], title: "The volcano", fact: "Volcanoes are openings where melted rock from deep inside the Earth escapes. Ash from big eruptions can block sunlight, and scientists study old ash layers to learn about the past." }, { at: [8, 11, 8], title: "Flying reptiles", fact: "Pterosaurs were flying reptiles, not dinosaurs. Their wings were skin stretched along one very long finger. Some were as small as a bird and some as wide as a small plane." }] },
];

const FACE = new Map<string, HTMLCanvasElement>();
export class Trip3D {
  renderer: THREE.WebGLRenderer; scene = new THREE.Scene(); cam = new THREE.PerspectiveCamera(70, 1, 0.1, 400); stereo: StereoEffect | null = null; vr = false; world = new THREE.Group(); ticks: Tick[] = []; trip!: Trip;
  yaw = 0; pitch = 0; gyro = false; ray = new THREE.Raycaster(); hot: { m: THREE.Mesh; s: Spot; seen: boolean }[] = []; dwell = 0; hover: Spot | null = null; t = 0; last = performance.now(); guide!: THREE.Sprite; guideCv = document.createElement("canvas"); guideTex = new THREE.CanvasTexture(this.guideCv); mouth = 0; speaking = false;
  onFact: (s: Spot, all: boolean) => void = () => { /* host sets */ }; onHover: (s: Spot | null, pct: number) => void = () => { /* host sets */ };
  constructor(public host: HTMLElement) {
    this.renderer = new THREE.WebGLRenderer({ antialias: true }); this.renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); host.appendChild(this.renderer.domElement); this.scene.add(this.world, new THREE.HemisphereLight(0xffffff, 0x888899, 1.9)); const sun = new THREE.DirectionalLight(0xffffff, 1.4); sun.position.set(5, 12, 4); this.scene.add(sun);
    this.cam.position.set(0, 1.6, 0); this.bind(); addEventListener("resize", () => this.resize()); this.resize(); requestAnimationFrame(this.frame);
  }
  resize() { const w = this.host.clientWidth || innerWidth, h = this.host.clientHeight || innerHeight; this.renderer.setSize(w, h); this.stereo?.setSize(w, h); this.cam.aspect = w / h; this.cam.updateProjectionMatrix(); }
  load(t: Trip) {
    this.trip = t; this.scene.remove(this.world); this.world = new THREE.Group(); this.scene.add(this.world); this.ticks = []; this.hot = [];
    const c = document.createElement("canvas"); c.width = 4; c.height = 256; const x = c.getContext("2d")!, gr = x.createLinearGradient(0, 0, 0, 256); gr.addColorStop(0, t.sky[1]); gr.addColorStop(1, t.sky[0]); x.fillStyle = gr; x.fillRect(0, 0, 4, 256);
    this.scene.background = new THREE.CanvasTexture(c); this.scene.fog = t.id === "space" ? null : new THREE.Fog(t.fog, 18, 80); t.build(this.world, this.ticks);
    for (const s of t.spots) { const g = new THREE.Group(); const orb = mesh(new THREE.SphereGeometry(0.42, 16, 12), new THREE.MeshBasicMaterial({ color: "#FFE27A", transparent: true, opacity: 0.85 })); const halo = mesh(new THREE.RingGeometry(0.6, 0.72, 32), new THREE.MeshBasicMaterial({ color: "#FFE27A", transparent: true, opacity: 0.8, side: THREE.DoubleSide })); g.add(orb, halo); g.position.set(...s.at); this.world.add(g); this.hot.push({ m: orb, s, seen: false }); this.ticks.push((time) => { orb.scale.setScalar(1 + Math.sin(time * 3 + s.at[0]) * 0.12); halo.lookAt(this.cam.position); }); }
    this.makeGuide(t); this.yaw = 0; this.pitch = 0;
  }
  private makeGuide(t: Trip) {
    const npc = TEACHER_BY_SUBJECT[t.subject === "history" ? "history" : "science"]; this.guideCv.width = 160; this.guideCv.height = 240; this.drawGuide(npc, 0);
    if (this.guide) this.scene.remove(this.guide); this.guideTex.needsUpdate = true; this.guide = new THREE.Sprite(new THREE.SpriteMaterial({ map: this.guideTex, transparent: true, depthTest: false })); this.guide.scale.set(1.5, 2.25, 1); this.guide.position.set(1.8, 1.0, -2.2); this.guide.renderOrder = 10; this.scene.add(this.guide); (this as any).npc = npc;
  }
  private drawGuide(npc: any, mouth: number) { const c = this.guideCv.getContext("2d")!; c.clearRect(0, 0, 160, 240); c.save(); c.translate(80, 228); c.scale(4.2, 4.2); drawChar(c, 0, 0, { ...npc.look, dir: "down", moving: false, walk: 0, mouth, tag: false }, 0); c.restore(); this.guideTex.needsUpdate = true; }
  get guideName() { return (this as any).npc?.name ?? "Your guide"; }
  talking(on: boolean) { this.speaking = on; if (!on) { this.drawGuide((this as any).npc, 0); } }
  private bind() {
    const el = this.renderer.domElement; let down = false, sx = 0, sy = 0, st = 0, moved = 0;
    el.addEventListener("pointerdown", (e) => { down = true; sx = e.clientX; sy = e.clientY; st = performance.now(); moved = 0; el.setPointerCapture(e.pointerId); });
    el.addEventListener("pointermove", (e) => { if (!down) return; const dx = e.clientX - sx, dy = e.clientY - sy; moved += Math.abs(dx) + Math.abs(dy); this.yaw += dx * 0.005; this.pitch = Math.max(-1.3, Math.min(1.3, this.pitch + dy * 0.004)); sx = e.clientX; sy = e.clientY; });
    el.addEventListener("pointerup", () => { if (down && moved < 8 && performance.now() - st < 500) this.activate(); down = false; });
    addEventListener("keydown", (e) => { const k = e.key; if (k === "ArrowLeft" || k === "a") this.yaw -= 0.1; else if (k === "ArrowRight" || k === "d") this.yaw += 0.1; else if (k === "ArrowUp" || k === "w") this.pitch = Math.min(1.3, this.pitch + 0.08); else if (k === "ArrowDown" || k === "s") this.pitch = Math.max(-1.3, this.pitch - 0.08); else if (k === " " || k === "Enter") this.activate(); });
  }
  /** use the phone's tilt to look around (iOS asks permission first) */
  async enableGyro(): Promise<boolean> {
    try { const D: any = (window as any).DeviceOrientationEvent; if (D?.requestPermission) { if ((await D.requestPermission()) !== "granted") return false; } let base: number | null = null;
      addEventListener("deviceorientation", (e: DeviceOrientationEvent) => { if (!this.gyro || e.alpha == null || e.beta == null) return; base ??= e.alpha; const scr = (screen.orientation?.angle ?? 0) * Math.PI / 180; this.yaw = -((e.alpha - base) * Math.PI) / 180 + (scr ? 0 : 0); this.pitch = Math.max(-1.3, Math.min(1.3, ((e.beta - 90) * Math.PI) / 180 * -1)); }); this.gyro = true; return true; } catch { return false; }
  }
  setVR(on: boolean) { this.vr = on; if (on && !this.stereo) { this.stereo = new StereoEffect(this.renderer); this.stereo.setSize(this.host.clientWidth, this.host.clientHeight); } this.resize(); }
  private aim() { this.ray.setFromCamera(new THREE.Vector2(0, 0), this.cam); const h = this.ray.intersectObjects(this.hot.map((x) => x.m), false); return h.length ? this.hot.find((x) => x.m === h[0].object)! : null; }
  private activate() { const h = this.aim(); if (h) this.fire(h); }
  private fire(h: { s: Spot; seen: boolean }) { h.seen = true; this.dwell = 0; this.onFact(h.s, this.hot.every((x) => x.seen)); }
  private frame = (now: number) => {
    const dt = Math.min(0.05, (now - this.last) / 1000); this.last = now; this.t += dt; for (const f of this.ticks) f(this.t, dt);
    this.cam.rotation.set(this.pitch, -this.yaw, 0, "YXZ");
    const h = this.aim(); if (h) { this.hover = h.s; this.dwell += dt; if (this.dwell > 1.8) this.fire(h); } else { this.hover = null; this.dwell = 0; } this.onHover(this.hover, Math.min(1, this.dwell / 1.8));
    if (this.speaking) { const o = Math.floor(this.t * 7) % 3; if (o !== this.mouth) { this.mouth = o; this.drawGuide((this as any).npc, [0.1, 0.7, 0.4][o]); } }
    if (this.guide) { this.guide.position.copy(this.cam.position).add(new THREE.Vector3(Math.sin(this.yaw + 0.2) * 2.8, -0.7 + this.pitch * -0.5, -Math.cos(this.yaw + 0.2) * 2.8)); }
    if (this.vr && this.stereo) this.stereo.render(this.scene, this.cam); else this.renderer.render(this.scene, this.cam); requestAnimationFrame(this.frame);
  };
}
void FACE;
