#!/usr/bin/env python3
"""Packs environment PNGs into one Phaser JSON-hash atlas; lists seat-view images and character sheets; emits assetManifest.ts."""
import json, os
from PIL import Image
from lib import ROOT, ASSET_DIR

L = lambda n: json.load(open(os.path.join(ROOT, "tools", n)))
allenv = L("env_manifest.json")
env = [e for e in allenv if e["category"] != "seatview"]
sv = [e for e in allenv if e["category"] == "seatview"]
ch = L("char_manifest.json")
PAD, MAXW = 2, 2048
x = y = rowh = 0
pos = {}
for e in sorted(env, key=lambda e: -e["h"]):
    if x + e["w"] + PAD > MAXW:
        x, y, rowh = 0, y + rowh + PAD, 0
    pos[e["key"]] = (x, y); x += e["w"] + PAD; rowh = max(rowh, e["h"])
H = y + rowh + PAD
atlas = Image.new("RGBA", (MAXW, H), (0, 0, 0, 0))
frames = {}
for e in env:
    im = Image.open(os.path.join(ASSET_DIR, e["file"])).convert("RGBA")
    px, py = pos[e["key"]]
    atlas.paste(im, (px, py))
    frames[e["key"]] = dict(frame=dict(x=px, y=py, w=e["w"], h=e["h"]), rotated=False, trimmed=False,
                            spriteSourceSize=dict(x=0, y=0, w=e["w"], h=e["h"]), sourceSize=dict(w=e["w"], h=e["h"]))
os.makedirs(os.path.join(ASSET_DIR, "atlas"), exist_ok=True)
atlas.save(os.path.join(ASSET_DIR, "atlas/auditorium_env.png"), optimize=True)
json.dump(dict(frames=frames, meta=dict(image="auditorium_env.png", size=dict(w=MAXW, h=H), scale="1", format="RGBA8888")),
          open(os.path.join(ASSET_DIR, "atlas/auditorium_env.json"), "w"))
sheets = [dict(key=s["key"], url=f"/assets/unify/{s['file']}", frames=s["frames"], fps=s["fps"], loop=s["loop"], character=s["character"],
               action=s["action"], fw=s["frameWidth"], fh=s["frameHeight"], dirs=s["dirs"], seatview=s["seatview"]) for s in ch["sheets"]]
images = [dict(key=e["key"], url=f"/assets/unify/{e['file']}") for e in sv]
ts = f"""// GENERATED by tools/pack_atlas.py - do not edit by hand.
export const ATLAS = {{ key: "auditorium_env", image: "/assets/unify/atlas/auditorium_env.png", data: "/assets/unify/atlas/auditorium_env.json" }} as const;
export const DIRECTIONS = {json.dumps(ch["directions"])} as const;
export type Direction = (typeof DIRECTIONS)[number];
export interface CharacterSheet {{ key: string; url: string; frames: number; fps: number; loop: boolean; character: string; action: string; fw: number; fh: number; dirs: string[]; seatview: boolean }}
export const CHARACTER_SHEETS: CharacterSheet[] = {json.dumps(sheets)};
export const SEATVIEW_IMAGES: {{ key: string; url: string }}[] = {json.dumps(images)};
export const ENV_KEYS: string[] = {json.dumps([e["key"] for e in env])};
"""
open(os.path.join(ROOT, "src/game/assets/assetManifest.ts"), "w").write(ts)
print(f"atlas {MAXW}x{H}, {len(frames)} frames; {len(sheets)} sheets; {len(images)} seatview images")
